"""
作者：鑫鑫鑫
微信：xinxinjijin8
日期：2025.01.02
未经作者允许，请勿转载
"""
# 推荐的fields:
recommended_fields = [
    'anl4_bvps_high / fnd6_recd', 
    'anl4_bvps_low / fnd6_newqv1300_recdq', 
    'anl4_bvps_low / fnd6_recd', 
    'anl4_bvps_low / news_eod_close', 
    'anl4_bvps_low / news_open', 
    'anl4_bvps_low / opt6_slcxp', 
    'anl4_capex_high / anl4_cfo_low', 
    'anl4_capex_high / anl4_cfo_median', 
    'anl4_capex_high / anl4_ebit_low', 
    'anl4_capex_high / anl4_ebit_median', 
    'anl4_capex_high / anl4_ebitda_high', 
    'anl4_capex_high / anl4_ebitda_low', 
    'anl4_capex_high / anl4_ebitda_value', 
    'anl4_capex_high / anl4_fcf_low', 
    'anl4_capex_high / anl4_gric_low', 
    'anl4_capex_high / anl4_gric_median', 
    'anl4_capex_high / anl4_medianepsbfam', 
    'anl4_capex_high / anl4_netdebt_low', 
    'anl4_capex_high / anl4_netdebt_median', 
    'anl4_capex_high / anl4_netprofit_high', 
    'anl4_capex_high / anl4_netprofit_low', 
    'anl4_capex_high / anl4_netprofit_median', 
    'anl4_capex_high / anl4_netprofit_value', 
    'anl4_capex_high / anl4_netprofita_high', 
    'anl4_capex_high / anl4_netprofita_low', 
    'anl4_capex_high / anl4_netprofita_median', 
    'anl4_capex_high / anl4_ptp_high', 
    'anl4_capex_high / anl4_ptp_low', 
    'anl4_capex_high / anl4_ptp_median', 
    'anl4_capex_high / anl4_ptp_value', 
    'anl4_capex_high / anl4_ptpr_high', 
    'anl4_capex_high / anl4_ptpr_low', 
    'anl4_capex_high / anl4_rd_exp_low', 
    'anl4_capex_high / anl4_totassets_low', 
    'anl4_capex_high / anl4_totassets_median', 
    'anl4_capex_high / est_ffo', 
    'anl4_capex_high / est_sales', 
    'anl4_capex_high / fnd2_a_blgandiprtsg', 
    'anl4_capex_high / fnd2_a_stkrpeprogramardamt', 
    'anl4_capex_high / fnd2_dbplanfvalpnas', 
    'anl4_capex_high / cashflow', 
    'anl4_capex_high / enterprise_value', 
    'anl4_capex_high / fnd6_acqgdwl', 
    'anl4_capex_high / fnd6_am', 
    'anl4_capex_high / fnd6_dcvt', 
    'anl4_capex_high / fnd6_dd', 
    'anl4_capex_high / fnd6_dd2', 
    'anl4_capex_high / fnd6_dd3', 
    'anl4_capex_high / fnd6_dd4', 
    'anl4_capex_high / fnd6_dd5', 
    'anl4_capex_high / fnd6_dltr', 
    'anl4_capex_high / fnd6_fatc', 
    'anl4_capex_high / fnd6_lcoxdr', 
    'anl4_capex_high / fnd6_newa1v1300_gp', 
    'anl4_capex_high / fnd6_newa1v1300_ibc', 
    'anl4_capex_high / fnd6_newa2v1300_oiadp', 
    'anl4_capex_high / fnd6_newa2v1300_oibdp', 
    'anl4_capex_high / fnd6_newa2v1300_ppent', 
    'anl4_capex_high / fnd6_newa2v1300_xsga', 
    'anl4_capex_high / fnd6_newqv1300_csh12q', 
    'anl4_capex_high / fnd6_newqv1300_ivltq', 
    'anl4_capex_high / fnd6_newqv1300_lltq', 
    'anl4_capex_high / fnd6_newqv1300_rcpq', 
    'anl4_capex_high / fnd6_newqv1300_recdq', 
    'anl4_capex_high / fnd6_niadj', 
    'anl4_capex_high / fnd6_rea', 
    'anl4_capex_high / fnd6_recd', 
    'anl4_capex_high / fnd6_tlcf', 
    'anl4_capex_high / income', 
    'anl4_capex_high / mdl38_iv_year_div', 
    'anl4_capex_high / star_val_earnings_projection_fy1', 
    'anl4_capex_high / star_val_earnings_projection_fy10', 
    'anl4_capex_high / star_val_earnings_projection_fy11', 
    'anl4_capex_high / star_val_earnings_projection_fy12', 
    'anl4_capex_high / star_val_earnings_projection_fy13', 
    'anl4_capex_high / star_val_earnings_projection_fy2', 
    'anl4_capex_high / star_val_earnings_projection_fy3', 
    'anl4_capex_high / star_val_earnings_projection_fy4', 
    'anl4_capex_high / star_val_earnings_projection_fy5', 
    'anl4_capex_high / star_val_earnings_projection_fy6', 
    'anl4_capex_high / star_val_earnings_projection_fy7', 
    'anl4_capex_high / star_val_earnings_projection_fy8', 
    'anl4_capex_high / star_val_earnings_projection_fy9', 
    'anl4_capex_high / pv13_revere_company_total', 
    'anl4_capex_high / pv13_revere_index_cap', 
    'anl4_capex_high / pv13_revere_key_sector_total', 
    'anl4_capex_high / pv13_revere_term_sector_total', 
    'anl4_capex_high / rel_num_comp', 
    'anl4_capex_high / rel_num_cust', 
    'anl4_capex_high / rel_num_part', 
    'anl4_capex_low / anl4_cfi_low', 
    'anl4_capex_low / anl4_cfo_low', 
    'anl4_capex_low / anl4_cfo_median', 
    'anl4_capex_low / anl4_ebit_low', 
    'anl4_capex_low / anl4_ebit_median', 
    'anl4_capex_low / anl4_ebitda_low', 
    'anl4_capex_low / anl4_fcf_low', 
    'anl4_capex_low / anl4_fcfps_low', 
    'anl4_capex_low / anl4_gric_low', 
    'anl4_capex_low / anl4_medianepsbfam', 
    'anl4_capex_low / anl4_netdebt_low', 
    'anl4_capex_low / anl4_netprofit_low', 
    'anl4_capex_low / anl4_netprofita_low', 
    'anl4_capex_low / anl4_netprofita_median', 
    'anl4_capex_low / anl4_ptp_high', 
    'anl4_capex_low / anl4_ptp_low', 
    'anl4_capex_low / anl4_ptp_median', 
    'anl4_capex_low / anl4_ptp_value', 
    'anl4_capex_low / anl4_ptpr_low', 
    'anl4_capex_low / anl4_ptpr_median', 
    'anl4_capex_low / anl4_rd_exp_low', 
    'anl4_capex_low / anl4_totassets_low', 
    'anl4_capex_low / fn_mne_a', 
    'anl4_capex_low / fnd2_a_dbplannpicbnfcst', 
    'anl4_capex_low / fnd2_a_flintasamt1expnext12m', 
    'anl4_capex_low / fnd2_a_rvndm', 
    'anl4_capex_low / cashflow', 
    'anl4_capex_low / enterprise_value', 
    'anl4_capex_low / fnd6_acqintan', 
    'anl4_capex_low / fnd6_am', 
    'anl4_capex_low / fnd6_aodo', 
    'anl4_capex_low / fnd6_dcvt', 
    'anl4_capex_low / fnd6_dd', 
    'anl4_capex_low / fnd6_dd1', 
    'anl4_capex_low / fnd6_dd2', 
    'anl4_capex_low / fnd6_dd3', 
    'anl4_capex_low / fnd6_dd4', 
    'anl4_capex_low / fnd6_dd5', 
    'anl4_capex_low / fnd6_dlcch', 
    'anl4_capex_low / fnd6_dltr', 
    'anl4_capex_low / fnd6_dn', 
    'anl4_capex_low / fnd6_ds', 
    'anl4_capex_low / fnd6_dudd', 
    'anl4_capex_low / fnd6_dvpa', 
    'anl4_capex_low / fnd6_fopo', 
    'anl4_capex_low / fnd6_fopox', 
    'anl4_capex_low / fnd6_invwip', 
    'anl4_capex_low / fnd6_ivch', 
    'anl4_capex_low / fnd6_newa1v1300_ao', 
    'anl4_capex_low / fnd6_newa1v1300_gp', 
    'anl4_capex_low / fnd6_newa2v1300_ni', 
    'anl4_capex_low / fnd6_newa2v1300_oiadp', 
    'anl4_capex_low / fnd6_newa2v1300_oibdp', 
    'anl4_capex_low / fnd6_newa2v1300_ppent', 
    'anl4_capex_low / fnd6_newa2v1300_rdip', 
    'anl4_capex_low / fnd6_newa2v1300_xsga', 
    'anl4_capex_low / fnd6_newqv1300_altoq', 
    'anl4_capex_low / fnd6_newqv1300_ivltq', 
    'anl4_capex_low / fnd6_newqv1300_lltq', 
    'anl4_capex_low / fnd6_newqv1300_rcpq', 
    'anl4_capex_low / fnd6_newqv1300_recdq', 
    'anl4_capex_low / fnd6_newqv1300_spcepq', 
    'anl4_capex_low / fnd6_niadj', 
    'anl4_capex_low / fnd6_npq', 
    'anl4_capex_low / fnd6_optca', 
    'anl4_capex_low / fnd6_rea', 
    'anl4_capex_low / fnd6_recd', 
    'anl4_capex_low / fnd6_recta', 
    'anl4_capex_low / fnd6_sstk', 
    'anl4_capex_low / fnd6_tlcf', 
    'anl4_capex_low / fnd6_txpd', 
    'anl4_capex_low / fnd6_xad', 
    'anl4_capex_low / fnd6_xrent', 
    'anl4_capex_low / income', 
    'anl4_capex_low / mdl38_iv_discount_rate', 
    'anl4_capex_low / mdl38_iv_div_payout_rate', 
    'anl4_capex_low / mdl38_iv_year_div', 
    'anl4_capex_low / star_val_earnings_projection_fy1', 
    'anl4_capex_low / star_val_earnings_projection_fy10', 
    'anl4_capex_low / star_val_earnings_projection_fy11', 
    'anl4_capex_low / star_val_earnings_projection_fy12', 
    'anl4_capex_low / star_val_earnings_projection_fy13', 
    'anl4_capex_low / star_val_earnings_projection_fy14', 
    'anl4_capex_low / star_val_earnings_projection_fy15', 
    'anl4_capex_low / star_val_earnings_projection_fy2', 
    'anl4_capex_low / star_val_earnings_projection_fy3', 
    'anl4_capex_low / star_val_earnings_projection_fy4', 
    'anl4_capex_low / star_val_earnings_projection_fy5', 
    'anl4_capex_low / star_val_earnings_projection_fy6', 
    'anl4_capex_low / star_val_earnings_projection_fy7', 
    'anl4_capex_low / star_val_earnings_projection_fy8', 
    'anl4_capex_low / star_val_earnings_projection_fy9', 
    'anl4_capex_low / news_dividend_yield', 
    'anl4_capex_low / news_eod_close', 
    'anl4_capex_low / news_eps_actual', 
    'anl4_capex_low / opt6_mktcap', 
    'anl4_capex_low / pv13_revere_company_total', 
    'anl4_capex_low / pv13_revere_index_cap', 
    'anl4_capex_low / pv13_revere_index_value', 
    'anl4_capex_low / pv13_revere_key_sector_total', 
    'anl4_capex_low / pv13_revere_term_sector_total', 
    'anl4_capex_low / rel_num_comp', 
    'anl4_capex_low / rel_num_cust', 
    'anl4_capex_low / rel_num_part', 
    'anl4_capex_low / vwap', 
    'anl4_capex_number / anl4_cfo_low', 
    'anl4_capex_number / fnd6_recd', 
    'anl4_capex_std / anl4_cfo_low', 
    'anl4_capex_std / anl4_cfo_median', 
    'anl4_capex_std / anl4_ebit_low', 
    'anl4_capex_std / anl4_ebitda_low', 
    'anl4_capex_std / anl4_ebitda_std', 
    'anl4_capex_std / anl4_fcf_low', 
    'anl4_capex_std / anl4_fcfps_low', 
    'anl4_capex_std / anl4_gric_low', 
    'anl4_capex_std / anl4_gric_std', 
    'anl4_capex_std / anl4_netprofit_low', 
    'anl4_capex_std / anl4_netprofita_low', 
    'anl4_capex_std / anl4_netprofita_median', 
    'anl4_capex_std / anl4_netprofita_std', 
    'anl4_capex_std / anl4_ptp_low', 
    'anl4_capex_std / anl4_ptpr_low', 
    'anl4_capex_std / anl4_rd_exp_low', 
    'anl4_capex_std / anl4_totassets_low', 
    'anl4_capex_std / anl4_totassets_std', 
    'anl4_capex_std / cashflow', 
    'anl4_capex_std / fnd6_dcvt', 
    'anl4_capex_std / fnd6_dltr', 
    'anl4_capex_std / fnd6_dudd', 
    'anl4_capex_std / fnd6_fatc', 
    'anl4_capex_std / fnd6_ivaco', 
    'anl4_capex_std / fnd6_newa2v1300_oiadp', 
    'anl4_capex_std / fnd6_newa2v1300_oibdp', 
    'anl4_capex_std / fnd6_newa2v1300_ppent', 
    'anl4_capex_std / fnd6_newqv1300_ivltq', 
    'anl4_capex_std / fnd6_newqv1300_recdq', 
    'anl4_capex_std / fnd6_rea', 
    'anl4_capex_std / fnd6_reajo', 
    'anl4_capex_std / fnd6_recd', 
    'anl4_capex_std / star_val_earnings_projection_fy1', 
    'anl4_capex_std / star_val_earnings_projection_fy2', 
    'anl4_capex_std / star_val_earnings_projection_fy3', 
    'anl4_capex_std / star_val_earnings_projection_fy4', 
    'anl4_capex_std / star_val_earnings_projection_fy8', 
    'anl4_capex_std / pv13_revere_key_sector_total', 
    'anl4_capex_std / pv13_revere_term_sector_total', 
    'anl4_capex_value / anl4_cff_low', 
    'anl4_capex_value / anl4_cfi_low', 
    'anl4_capex_value / anl4_cfo_low', 
    'anl4_capex_value / anl4_cfo_value', 
    'anl4_capex_value / anl4_ebitda_low', 
    'anl4_capex_value / anl4_ebitda_value', 
    'anl4_capex_value / anl4_fcf_low', 
    'anl4_capex_value / anl4_fcf_value', 
    'anl4_capex_value / anl4_fcfps_low', 
    'anl4_capex_value / anl4_gric_low', 
    'anl4_capex_value / anl4_netdebt_low', 
    'anl4_capex_value / anl4_netprofit_low', 
    'anl4_capex_value / anl4_netprofita_low', 
    'anl4_capex_value / anl4_netprofita_median', 
    'anl4_capex_value / anl4_ptp_low', 
    'anl4_capex_value / anl4_ptpr_low', 
    'anl4_capex_value / anl4_totassets_low', 
    'anl4_capex_value / est_ffo', 
    'anl4_capex_value / fn_mne_a', 
    'anl4_capex_value / cashflow', 
    'anl4_capex_value / enterprise_value', 
    'anl4_capex_value / fnd6_dcvt', 
    'anl4_capex_value / fnd6_dd1', 
    'anl4_capex_value / fnd6_dd2', 
    'anl4_capex_value / fnd6_dd3', 
    'anl4_capex_value / fnd6_dd4', 
    'anl4_capex_value / fnd6_dd5', 
    'anl4_capex_value / fnd6_intc', 
    'anl4_capex_value / fnd6_newa1v1300_gp', 
    'anl4_capex_value / fnd6_newa1v1300_ibc', 
    'anl4_capex_value / fnd6_newa2v1300_ni', 
    'anl4_capex_value / fnd6_newa2v1300_oiadp', 
    'anl4_capex_value / fnd6_newa2v1300_oibdp', 
    'anl4_capex_value / fnd6_newa2v1300_ppegt', 
    'anl4_capex_value / fnd6_newa2v1300_ppent', 
    'anl4_capex_value / fnd6_newa2v1300_xsga', 
    'anl4_capex_value / fnd6_newqv1300_altoq', 
    'anl4_capex_value / fnd6_newqv1300_ivltq', 
    'anl4_capex_value / fnd6_newqv1300_lltq', 
    'anl4_capex_value / fnd6_newqv1300_rcpq', 
    'anl4_capex_value / fnd6_newqv1300_seqq', 
    'anl4_capex_value / fnd6_newqv1300_spcep12', 
    'anl4_capex_value / fnd6_niadj', 
    'anl4_capex_value / fnd6_npq', 
    'anl4_capex_value / fnd6_rea', 
    'anl4_capex_value / fnd6_recd', 
    'anl4_capex_value / fnd6_sstk', 
    'anl4_capex_value / fnd6_xad', 
    'anl4_capex_value / fnd6_xrent', 
    'anl4_capex_value / income', 
    'anl4_capex_value / star_val_earnings_projection_fy1', 
    'anl4_capex_value / star_val_earnings_projection_fy14', 
    'anl4_capex_value / star_val_earnings_projection_fy15', 
    'anl4_capex_value / star_val_earnings_projection_fy2', 
    'anl4_capex_value / star_val_earnings_projection_fy3', 
    'anl4_capex_value / star_val_earnings_projection_fy4', 
    'anl4_capex_value / star_val_earnings_projection_fy5', 
    'anl4_capex_value / star_val_earnings_projection_fy7', 
    'anl4_capex_value / star_val_earnings_projection_fy8', 
    'anl4_capex_value / star_val_earnings_projection_fy9', 
    'anl4_capex_value / news_dividend_yield', 
    'anl4_capex_value / news_main_vwap', 
    'anl4_capex_value / opt6_mktcap', 
    'anl4_capex_value / opt6_slcxp', 
    'anl4_capex_value / opt6_xpslcy1', 
    'anl4_capex_value / pv13_revere_company_total', 
    'anl4_capex_value / pv13_revere_index_cap', 
    'anl4_capex_value / pv13_revere_key_sector_total', 
    'anl4_capex_value / pv13_revere_term_sector_total', 
    'anl4_capex_value / rel_num_cust', 
    'anl4_capex_value / rel_num_part', 
    'anl4_cff_high / anl4_cfo_low', 
    'anl4_cff_high / anl4_ebitda_low', 
    'anl4_cff_high / anl4_gric_low', 
    'anl4_cff_high / anl4_netdebt_low', 
    'anl4_cff_high / anl4_netprofita_low', 
    'anl4_cff_high / anl4_ptp_low', 
    'anl4_cff_high / anl4_ptp_median', 
    'anl4_cff_high / anl4_ptpr_low', 
    'anl4_cff_high / fnd6_dd5', 
    'anl4_cff_high / fnd6_dltr', 
    'anl4_cff_high / fnd6_newa2v1300_oiadp', 
    'anl4_cff_high / fnd6_newqv1300_lltq', 
    'anl4_cff_high / star_val_earnings_projection_fy2', 
    'anl4_cff_high / star_val_earnings_projection_fy3', 
    'anl4_cff_high / star_val_earnings_projection_fy4', 
    'anl4_cff_high / star_val_earnings_projection_fy5', 
    'anl4_cff_high / star_val_earnings_projection_fy6', 
    'anl4_cff_high / pv13_revere_term_sector_total', 
    'anl4_cff_high / rel_num_part', 
    'anl4_cff_low / anl4_ebitda_low', 
    'anl4_cff_low / anl4_fcf_low', 
    'anl4_cff_low / anl4_gric_low', 
    'anl4_cff_low / anl4_netdebt_low', 
    'anl4_cff_low / anl4_netprofit_low', 
    'anl4_cff_low / anl4_netprofita_low', 
    'anl4_cff_low / anl4_ptp_low', 
    'anl4_cff_low / anl4_ptpr_low', 
    'anl4_cff_low / anl4_totassets_low', 
    'anl4_cff_low / fn_new_shares_issued_a', 
    'anl4_cff_low / cashflow', 
    'anl4_cff_low / debt', 
    'anl4_cff_low / enterprise_value', 
    'anl4_cff_low / fnd6_dcvt', 
    'anl4_cff_low / fnd6_dd2', 
    'anl4_cff_low / fnd6_dd3', 
    'anl4_cff_low / fnd6_dd4', 
    'anl4_cff_low / fnd6_dd5', 
    'anl4_cff_low / fnd6_ds', 
    'anl4_cff_low / fnd6_newa2v1300_oiadp', 
    'anl4_cff_low / fnd6_newqv1300_lltq', 
    'anl4_cff_low / fnd6_newqv1300_rcpq', 
    'anl4_cff_low / fnd6_newqv1300_recdq', 
    'anl4_cff_low / fnd6_niadj', 
    'anl4_cff_low / fnd6_rea', 
    'anl4_cff_low / fnd6_recd', 
    'anl4_cff_low / income', 
    'anl4_cff_low / mdl38_iv_discount_rate', 
    'anl4_cff_low / mdl38_iv_year_div', 
    'anl4_cff_low / star_val_earnings_projection_fy1', 
    'anl4_cff_low / star_val_earnings_projection_fy10', 
    'anl4_cff_low / star_val_earnings_projection_fy12', 
    'anl4_cff_low / star_val_earnings_projection_fy2', 
    'anl4_cff_low / star_val_earnings_projection_fy3', 
    'anl4_cff_low / star_val_earnings_projection_fy4', 
    'anl4_cff_low / star_val_earnings_projection_fy5', 
    'anl4_cff_low / star_val_earnings_projection_fy6', 
    'anl4_cff_low / star_val_earnings_projection_fy7', 
    'anl4_cff_low / star_val_earnings_projection_fy8', 
    'anl4_cff_low / star_val_earnings_projection_fy9', 
    'anl4_cff_low / news_open', 
    'anl4_cff_low / opt6_divamt', 
    'anl4_cff_low / opt6_divfreq', 
    'anl4_cff_low / opt6_slcxp', 
    'anl4_cff_low / opt6_xpslcy1', 
    'anl4_cff_low / pv13_revere_company_total', 
    'anl4_cff_low / pv13_revere_key_sector_total', 
    'anl4_cff_low / pv13_revere_term_sector_total', 
    'anl4_cff_low / rel_num_comp', 
    'anl4_cff_low / rel_num_part', 
    'anl4_cff_median / anl4_fcf_median', 
    'anl4_cff_median / anl4_netprofit_low', 
    'anl4_cff_median / anl4_ptp_low', 
    'anl4_cff_median / star_val_earnings_projection_fy1', 
    'anl4_cff_median / star_val_earnings_projection_fy2', 
    'anl4_cff_median / star_val_earnings_projection_fy3', 
    'anl4_cff_median / star_val_earnings_projection_fy4', 
    'anl4_cff_median / star_val_earnings_projection_fy7', 
    'anl4_cff_median / opt6_slcxp', 
    'anl4_cff_median / opt6_xpslcm1', 
    'anl4_cff_median / opt6_xpslcy1', 
    'anl4_cff_value / anl4_fcf_low', 
    'anl4_cff_value / anl4_netprofit_low', 
    'anl4_cff_value / fn_new_shares_issued_a', 
    'anl4_cff_value / fnd6_dltr', 
    'anl4_cfi_high / anl4_cfo_low', 
    'anl4_cfi_high / anl4_ebit_low', 
    'anl4_cfi_high / anl4_ebitda_low', 
    'anl4_cfi_high / anl4_fcf_low', 
    'anl4_cfi_high / anl4_gric_low', 
    'anl4_cfi_high / anl4_netdebt_low', 
    'anl4_cfi_high / anl4_netprofit_low', 
    'anl4_cfi_high / anl4_netprofita_low', 
    'anl4_cfi_high / anl4_ptp_low', 
    'anl4_cfi_high / anl4_ptpr_low', 
    'anl4_cfi_high / anl4_totassets_low', 
    'anl4_cfi_high / cashflow', 
    'anl4_cfi_high / enterprise_value', 
    'anl4_cfi_high / fnd6_newa2v1300_oiadp', 
    'anl4_cfi_high / fnd6_newqv1300_lltq', 
    'anl4_cfi_high / fnd6_newqv1300_recdq', 
    'anl4_cfi_high / fnd6_niadj', 
    'anl4_cfi_high / fnd6_recd', 
    'anl4_cfi_high / star_val_earnings_projection_fy1', 
    'anl4_cfi_high / star_val_earnings_projection_fy3', 
    'anl4_cfi_high / pv13_revere_term_sector_total', 
    'anl4_cfi_high / rel_num_part', 
    'anl4_cfi_low / anl4_cfo_low', 
    'anl4_cfi_low / anl4_ebit_low', 
    'anl4_cfi_low / anl4_ebitda_low', 
    'anl4_cfi_low / anl4_fcf_low', 
    'anl4_cfi_low / anl4_fcf_median', 
    'anl4_cfi_low / anl4_gric_low', 
    'anl4_cfi_low / anl4_netdebt_low', 
    'anl4_cfi_low / anl4_netprofit_low', 
    'anl4_cfi_low / anl4_netprofita_low', 
    'anl4_cfi_low / anl4_netprofita_median', 
    'anl4_cfi_low / anl4_netprofita_std', 
    'anl4_cfi_low / anl4_ptp_low', 
    'anl4_cfi_low / anl4_ptpr_low', 
    'anl4_cfi_low / anl4_totassets_low', 
    'anl4_cfi_low / cashflow', 
    'anl4_cfi_low / enterprise_value', 
    'anl4_cfi_low / fnd6_dcvt', 
    'anl4_cfi_low / fnd6_dd2', 
    'anl4_cfi_low / fnd6_dd3', 
    'anl4_cfi_low / fnd6_dd4', 
    'anl4_cfi_low / fnd6_dd5', 
    'anl4_cfi_low / fnd6_fopox', 
    'anl4_cfi_low / fnd6_newa1v1300_gp', 
    'anl4_cfi_low / fnd6_newa2v1300_ni', 
    'anl4_cfi_low / fnd6_newa2v1300_oiadp', 
    'anl4_cfi_low / fnd6_newa2v1300_oibdp', 
    'anl4_cfi_low / fnd6_newqv1300_ivltq', 
    'anl4_cfi_low / fnd6_newqv1300_lltq', 
    'anl4_cfi_low / fnd6_newqv1300_recdq', 
    'anl4_cfi_low / fnd6_niadj', 
    'anl4_cfi_low / fnd6_recd', 
    'anl4_cfi_low / income', 
    'anl4_cfi_low / mdl38_iv_year_div', 
    'anl4_cfi_low / star_val_earnings_projection_fy1', 
    'anl4_cfi_low / star_val_earnings_projection_fy10', 
    'anl4_cfi_low / star_val_earnings_projection_fy11', 
    'anl4_cfi_low / star_val_earnings_projection_fy12', 
    'anl4_cfi_low / star_val_earnings_projection_fy15', 
    'anl4_cfi_low / star_val_earnings_projection_fy2', 
    'anl4_cfi_low / star_val_earnings_projection_fy3', 
    'anl4_cfi_low / star_val_earnings_projection_fy4', 
    'anl4_cfi_low / star_val_earnings_projection_fy5', 
    'anl4_cfi_low / star_val_earnings_projection_fy6', 
    'anl4_cfi_low / star_val_earnings_projection_fy7', 
    'anl4_cfi_low / star_val_earnings_projection_fy8', 
    'anl4_cfi_low / star_val_earnings_projection_fy9', 
    'anl4_cfi_low / opt6_xpslcm1', 
    'anl4_cfi_low / pv13_revere_index_value', 
    'anl4_cfi_low / pv13_revere_key_sector_total', 
    'anl4_cfi_low / pv13_revere_term_sector_total', 
    'anl4_cfi_low / rel_num_comp', 
    'anl4_cfi_low / rel_num_part', 
    'anl4_cfi_median / anl4_cfo_median', 
    'anl4_cfi_median / anl4_ebitda_low', 
    'anl4_cfi_median / anl4_fcf_low', 
    'anl4_cfi_median / anl4_fcf_median', 
    'anl4_cfi_median / anl4_netprofit_low', 
    'anl4_cfi_median / anl4_netprofita_low', 
    'anl4_cfi_median / anl4_netprofita_median', 
    'anl4_cfi_median / anl4_ptp_low', 
    'anl4_cfi_median / anl4_ptp_median', 
    'anl4_cfi_median / cashflow', 
    'anl4_cfi_median / fnd6_dcvt', 
    'anl4_cfi_median / fnd6_dd5', 
    'anl4_cfi_median / fnd6_newa2v1300_oiadp', 
    'anl4_cfi_median / fnd6_newa2v1300_oibdp', 
    'anl4_cfi_median / star_val_earnings_projection_fy1', 
    'anl4_cfi_median / star_val_earnings_projection_fy2', 
    'anl4_cfi_median / star_val_earnings_projection_fy3', 
    'anl4_cfi_median / star_val_earnings_projection_fy4', 
    'anl4_cfi_median / star_val_earnings_projection_fy5', 
    'anl4_cfi_median / star_val_earnings_projection_fy9', 
    'anl4_cfi_median / opt6_xpslcy1', 
    'anl4_cfi_value / anl4_fcf_low', 
    'anl4_cfi_value / anl4_netprofit_low', 
    'anl4_cfi_value / anl4_ptp_low', 
    'anl4_cfo_high / anl4_cfo_value', 
    'anl4_cfo_high / anl4_ebitda_low', 
    'anl4_cfo_high / anl4_netprofit_low', 
    'anl4_cfo_high / anl4_netprofit_median', 
    'anl4_cfo_high / anl4_netprofita_low', 
    'anl4_cfo_high / anl4_ptp_low', 
    'anl4_cfo_high / anl4_ptp_median', 
    'anl4_cfo_high / anl4_ptpr_low', 
    'anl4_cfo_high / anl4_totassets_low', 
    'anl4_cfo_high / fnd2_oprlsfmpdcurr', 
    'anl4_cfo_high / fnd6_dd2', 
    'anl4_cfo_high / fnd6_dd3', 
    'anl4_cfo_high / fnd6_dd5', 
    'anl4_cfo_high / fnd6_newa1v1300_dvc', 
    'anl4_cfo_high / fnd6_newa2v1300_oiadp', 
    'anl4_cfo_high / fnd6_newa2v1300_oibdp', 
    'anl4_cfo_high / fnd6_newqv1300_lltq', 
    'anl4_cfo_high / fnd6_newqv1300_recdq', 
    'anl4_cfo_high / fnd6_recd', 
    'anl4_cfo_high / fscore_profitability', 
    'anl4_cfo_high / mdl38_iv_year_div', 
    'anl4_cfo_high / star_val_earnings_projection_fy1', 
    'anl4_cfo_high / star_val_earnings_projection_fy2', 
    'anl4_cfo_high / star_val_earnings_projection_fy3', 
    'anl4_cfo_high / star_val_earnings_projection_fy4', 
    'anl4_cfo_high / star_val_earnings_projection_fy7', 
    'anl4_cfo_high / star_val_earnings_projection_fy8',
     'anl4_cfo_high / star_val_earnings_projection_fy9', 
     'anl4_cfo_high / opt6_vimtaxp', 
     'anl4_cfo_high / opt6_xpslcy1', 
     'anl4_cfo_high / pv13_revere_company_total', 
    'anl4_cfo_high / pv13_revere_key_sector_total', 
    'anl4_cfo_high / pv13_revere_term_sector_total', 
    'anl4_cfo_low / anl4_ebit_low', 
    'anl4_cfo_low / anl4_ebitda_low', 
    'anl4_cfo_low / anl4_fcf_low', 
    'anl4_cfo_low / anl4_gric_low', 
    'anl4_cfo_low / anl4_netdebt_low', 
    'anl4_cfo_low / anl4_netprofit_low', 
    'anl4_cfo_low / anl4_netprofita_low', 
    'anl4_cfo_low / anl4_ptp_low', 
    'anl4_cfo_low / anl4_ptpr_low', 
    'anl4_cfo_low / est_ffo', 
    'anl4_cfo_low / fn_op_lease_min_pay_due_a', 
    'anl4_cfo_low / fn_op_lease_min_pay_due_in_2y_a', 
    'anl4_cfo_low / fnd2_a_ltrmdmrepoplinnext12m', 
    'anl4_cfo_low / fnd2_a_rvndm', 
    'anl4_cfo_low / fnd2_oprlsfmpdcurr', 
    'anl4_cfo_low / cashflow', 
    'anl4_cfo_low / debt', 
    'anl4_cfo_low / enterprise_value', 
    'anl4_cfo_low / fnd6_am', 
    'anl4_cfo_low / fnd6_beta', 
    'anl4_cfo_low / fnd6_dcvt', 
    'anl4_cfo_low / fnd6_dd1q', 
    'anl4_cfo_low / fnd6_dd2', 
    'anl4_cfo_low / fnd6_dd3', 
    'anl4_cfo_low / fnd6_dd4', 
    'anl4_cfo_low / fnd6_dd5', 
    'anl4_cfo_low / fnd6_ds', 
    'anl4_cfo_low / fnd6_dudd', 
    'anl4_cfo_low / fnd6_dvpa', 
    'anl4_cfo_low / fnd6_lcoxdr', 
    'anl4_cfo_low / fnd6_newa1v1300_dvc', 
    'anl4_cfo_low / fnd6_newa2v1300_oiadp', 
    'anl4_cfo_low / fnd6_newa2v1300_oibdp', 
    'anl4_cfo_low / fnd6_newa2v1300_ppent', 
    'anl4_cfo_low / fnd6_newqv1300_ivltq', 
    'anl4_cfo_low / fnd6_newqv1300_lltq', 
    'anl4_cfo_low / fnd6_newqv1300_rcpq', 
    'anl4_cfo_low / fnd6_newqv1300_recdq', 
    'anl4_cfo_low / fnd6_newqv1300_spcepq', 
    'anl4_cfo_low / fnd6_niadj', 
    'anl4_cfo_low / fnd6_npq', 
    'anl4_cfo_low / fnd6_pifo', 
    'anl4_cfo_low / fnd6_rea', 
    'anl4_cfo_low / fnd6_recd', 
    'anl4_cfo_low / fnd6_txpd', 
    'anl4_cfo_low / fnd6_xad', 
    'anl4_cfo_low / fnd6_xrent', 
    'anl4_cfo_low / income', 
    'anl4_cfo_low / fscore_profitability', 
    'anl4_cfo_low / mdl38_iv_discount_rate', 
    'anl4_cfo_low / mdl38_iv_div_payout_rate', 
    'anl4_cfo_low / mdl38_iv_year_div', 
    'anl4_cfo_low / star_val_dividend_projection_fy1', 
    'anl4_cfo_low / star_val_dividend_projection_fy11', 
    'anl4_cfo_low / star_val_dividend_projection_fy12', 
    'anl4_cfo_low / star_val_dividend_projection_fy15', 
    'anl4_cfo_low / star_val_dividend_projection_fy2', 
    'anl4_cfo_low / star_val_dividend_projection_fy3', 
    'anl4_cfo_low / star_val_dividend_projection_fy8', 
    'anl4_cfo_low / star_val_earnings_projection_fy1', 
    'anl4_cfo_low / star_val_earnings_projection_fy10', 
    'anl4_cfo_low / star_val_earnings_projection_fy11', 
    'anl4_cfo_low / star_val_earnings_projection_fy12', 
    'anl4_cfo_low / star_val_earnings_projection_fy13', 
    'anl4_cfo_low / star_val_earnings_projection_fy14', 
    'anl4_cfo_low / star_val_earnings_projection_fy15', 
    'anl4_cfo_low / star_val_earnings_projection_fy2', 
    'anl4_cfo_low / star_val_earnings_projection_fy3', 
    'anl4_cfo_low / star_val_earnings_projection_fy4', 
    'anl4_cfo_low / star_val_earnings_projection_fy5', 
    'anl4_cfo_low / star_val_earnings_projection_fy6', 
    'anl4_cfo_low / star_val_earnings_projection_fy7', 
    'anl4_cfo_low / star_val_earnings_projection_fy8', 
    'anl4_cfo_low / star_val_earnings_projection_fy9', 
    'anl4_cfo_low / news_dividend_yield', 
    'anl4_cfo_low / news_eod_vwap', 
    'anl4_cfo_low / news_open', 
    'anl4_cfo_low / news_pe_ratio', 
    'anl4_cfo_low / opt6_divamt', 
    'anl4_cfo_low / opt6_divfreq', 
    'anl4_cfo_low / opt6_slcxp', 
    'anl4_cfo_low / pv13_revere_company_total', 
    'anl4_cfo_low / pv13_revere_index_cap', 
    'anl4_cfo_low / pv13_revere_index_value', 
    'anl4_cfo_low / pv13_revere_key_sector_total', 
    'anl4_cfo_low / pv13_revere_term_sector_total', 
    'anl4_cfo_low / rel_num_comp', 
    'anl4_cfo_low / rel_num_cust', 
    'anl4_cfo_low / rel_num_part', 
    'anl4_cfo_low / dividend', 
    'anl4_cfo_median / anl4_fcf_low', 
    'anl4_cfo_median / anl4_fcf_median', 
    'anl4_cfo_median / anl4_median_capexp', 
    'anl4_cfo_median / anl4_medianepsbfam', 
    'anl4_cfo_median / anl4_netdebt_median', 
    'anl4_cfo_median / anl4_netprofit_median', 
    'anl4_cfo_median / anl4_netprofita_median', 
    'anl4_cfo_median / anl4_ptp_low', 
    'anl4_cfo_median / anl4_ptp_median', 
    'anl4_cfo_median / anl4_ptpr_median', 
    'anl4_cfo_median / anl4_totassets_median', 
    'anl4_cfo_median / fnd2_oprlsfmpdcurr', 
    'anl4_cfo_median / debt', 
    'anl4_cfo_median / enterprise_value', 
    'anl4_cfo_median / fnd6_dcvt', 
    'anl4_cfo_median / fnd6_dd1', 
    'anl4_cfo_median / fnd6_dd1q', 
    'anl4_cfo_median / fnd6_dd2', 
    'anl4_cfo_median / fnd6_dd3', 
    'anl4_cfo_median / fnd6_dd5', 
    'anl4_cfo_median / fnd6_dltr', 
    'anl4_cfo_median / fnd6_dudd', 
    'anl4_cfo_median / fnd6_fopo', 
    'anl4_cfo_median / fnd6_newa1v1300_gp', 
    'anl4_cfo_median / fnd6_newa2v1300_ni', 
    'anl4_cfo_median / fnd6_newa2v1300_oiadp', 
    'anl4_cfo_median / fnd6_newa2v1300_oibdp', 
    'anl4_cfo_median / fnd6_newa2v1300_ppent', 
    'anl4_cfo_median / fnd6_newqv1300_lltq', 
    'anl4_cfo_median / fnd6_rea', 
    'anl4_cfo_median / fnd6_recd', 
    'anl4_cfo_median / income', 
    'anl4_cfo_median / mdl38_iv_div_payout_rate', 
    'anl4_cfo_median / mdl38_iv_year_div', 
    'anl4_cfo_median / star_val_dividend_projection_fy1', 
    'anl4_cfo_median / star_val_dividend_projection_fy3', 
    'anl4_cfo_median / star_val_dividend_projection_fy8', 
    'anl4_cfo_median / star_val_dividend_projection_fy9', 
    'anl4_cfo_median / star_val_earnings_projection_fy1', 
    'anl4_cfo_median / star_val_earnings_projection_fy10', 
    'anl4_cfo_median / star_val_earnings_projection_fy12', 
    'anl4_cfo_median / star_val_earnings_projection_fy13', 
    'anl4_cfo_median / star_val_earnings_projection_fy14', 
    'anl4_cfo_median / star_val_earnings_projection_fy15', 
    'anl4_cfo_median / star_val_earnings_projection_fy2', 
    'anl4_cfo_median / star_val_earnings_projection_fy3', 
    'anl4_cfo_median / star_val_earnings_projection_fy4', 
    'anl4_cfo_median / star_val_earnings_projection_fy5', 
    'anl4_cfo_median / star_val_earnings_projection_fy6', 
    'anl4_cfo_median / star_val_earnings_projection_fy7', 
    'anl4_cfo_median / star_val_earnings_projection_fy8', 
    'anl4_cfo_median / star_val_earnings_projection_fy9', 
    'anl4_cfo_median / opt6_divamt', 
    'anl4_cfo_median / opt6_divfreq', 
    'anl4_cfo_median / opt6_slcxp', 
    'anl4_cfo_median / opt6_xpslcm1', 
    'anl4_cfo_median / opt6_xpslcy1', 
    'anl4_cfo_median / pv13_revere_index_value', 
    'anl4_cfo_median / pv13_revere_term_sector_total', 
    'anl4_cfo_median / dividend', 
    'anl4_cfo_value / anl4_ebit_low', 
    'anl4_cfo_value / anl4_ebitda_low', 
    'anl4_cfo_value / anl4_fcf_low', 
    'anl4_cfo_value / anl4_gric_low', 
    'anl4_cfo_value / anl4_netdebt_low', 
    'anl4_cfo_value / anl4_netprofit_low', 
    'anl4_cfo_value / anl4_netprofita_low', 
    'anl4_cfo_value / anl4_ptp_low', 
    'anl4_cfo_value / anl4_ptpr_low', 
    'anl4_cfo_value / fn_op_lease_rent_exp_a', 
    'anl4_cfo_value / fnd2_oprlsfmpdcurr', 
    'anl4_cfo_value / debt', 
    'anl4_cfo_value / fnd6_dcvt', 
    'anl4_cfo_value / fnd6_dd1', 
    'anl4_cfo_value / fnd6_dd2', 
    'anl4_cfo_value / fnd6_dd5', 
    'anl4_cfo_value / fnd6_lcoxdr', 
    'anl4_cfo_value / fnd6_newa1v1300_dvc', 
    'anl4_cfo_value / fnd6_newa2v1300_ni', 
    'anl4_cfo_value / fnd6_newa2v1300_oiadp', 
    'anl4_cfo_value / fnd6_newa2v1300_oibdp', 
    'anl4_cfo_value / fnd6_newqv1300_lltq', 
    'anl4_cfo_value / fnd6_newqv1300_recdq', 
    'anl4_cfo_value / fnd6_niadj', 
    'anl4_cfo_value / fnd6_recd', 
    'anl4_cfo_value / income', 
    'anl4_cfo_value / mdl38_iv_year_div', 
    'anl4_cfo_value / star_val_earnings_projection_fy1', 
    'anl4_cfo_value / pv13_revere_term_sector_total', 
    'anl4_cfo_value / rel_num_cust', 
    'anl4_cfo_value / rel_num_part', 
    'anl4_dts_ptp / anl4_ebitda_high', 
    'anl4_dts_ptp / anl4_ebitda_low', 
    'anl4_dts_ptp / anl4_ebitda_std', 
    'anl4_dts_ptp / fnd6_dltr', 
    'anl4_dts_ptp / fnd6_ds', 
    'anl4_dts_ptp / fnd6_fopo', 
    'anl4_dts_ptp / fnd6_newa2v1300_oiadp', 
    'anl4_dts_ptp / fnd6_newa2v1300_oibdp', 
    'anl4_dts_ptp / fnd6_newqv1300_recdq', 
    'anl4_dts_ptp / fnd6_recd', 
    'anl4_dts_ptp / star_val_earnings_projection_fy1', 
    'anl4_dts_ptp / pv13_revere_term_sector_total', 
    'anl4_dts_ptp / rel_num_part', 
    'anl4_ebit_high / anl4_ebitda_low', 
    'anl4_ebit_high / anl4_medianepsbfam', 
    'anl4_ebit_high / anl4_ptp_low', 
    'anl4_ebit_high / anl4_totassets_low', 
    'anl4_ebit_high / enterprise_value', 
    'anl4_ebit_high / fnd6_dudd', 
    'anl4_ebit_high / fnd6_newa2v1300_oibdp', 
    'anl4_ebit_high / fnd6_newqv1300_recdq', 
    'anl4_ebit_high / fnd6_pifo', 
    'anl4_ebit_high / fnd6_rea', 
    'anl4_ebit_high / fnd6_recd', 
    'anl4_ebit_high / mdl38_iv_discount_rate', 
    'anl4_ebit_high / star_val_earnings_projection_fy4', 
    'anl4_ebit_low / anl4_ebitda_low', 
    'anl4_ebit_low / anl4_fcf_low', 
    'anl4_ebit_low / anl4_netprofita_low', 
    'anl4_ebit_low / anl4_ptp_low', 
    'anl4_ebit_low / anl4_ptpr_low', 
    'anl4_ebit_low / anl4_totassets_low', 
    'anl4_ebit_low / fn_op_lease_rent_exp_a', 
    'anl4_ebit_low / fnd2_a_rvndm', 
    'anl4_ebit_low / cashflow', 
    'anl4_ebit_low / enterprise_value', 
    'anl4_ebit_low / fnd6_acqintan', 
    'anl4_ebit_low / fnd6_beta', 
    'anl4_ebit_low / fnd6_dcvsub', 
    'anl4_ebit_low / fnd6_dcvt', 
    'anl4_ebit_low / fnd6_dd3', 
    'anl4_ebit_low / fnd6_dd4', 
    'anl4_ebit_low / fnd6_dltr', 
    'anl4_ebit_low / fnd6_dudd', 
    'anl4_ebit_low / fnd6_fopo', 
    'anl4_ebit_low / fnd6_newa2v1300_oiadp', 
    'anl4_ebit_low / fnd6_newa2v1300_oibdp', 
    'anl4_ebit_low / fnd6_newa2v1300_ppent', 
    'anl4_ebit_low / fnd6_newa2v1300_xsga', 
    'anl4_ebit_low / fnd6_newqv1300_ivltq', 
    'anl4_ebit_low / fnd6_newqv1300_rcpq', 
    'anl4_ebit_low / fnd6_newqv1300_recdq', 
    'anl4_ebit_low / fnd6_pifo', 
    'anl4_ebit_low / fnd6_recd', 
    'anl4_ebit_low / fnd6_xad', 
    'anl4_ebit_low / fnd6_xrent', 
    'anl4_ebit_low / fscore_quality', 
    'anl4_ebit_low / mdl38_iv_discount_rate', 
    'anl4_ebit_low / star_val_earnings_projection_fy1', 
    'anl4_ebit_low / star_val_earnings_projection_fy11', 
    'anl4_ebit_low / star_val_earnings_projection_fy12', 
    'anl4_ebit_low / star_val_earnings_projection_fy13', 
    'anl4_ebit_low / star_val_earnings_projection_fy14', 
    'anl4_ebit_low / star_val_earnings_projection_fy15', 
    'anl4_ebit_low / star_val_earnings_projection_fy2', 
    'anl4_ebit_low / star_val_earnings_projection_fy3', 
    'anl4_ebit_low / star_val_earnings_projection_fy4', 
    'anl4_ebit_low / star_val_earnings_projection_fy5', 
    'anl4_ebit_low / star_val_earnings_projection_fy6', 
    'anl4_ebit_low / star_val_earnings_projection_fy7', 
    'anl4_ebit_low / star_val_earnings_projection_fy8', 
    'anl4_ebit_low / star_val_earnings_projection_fy9', 
    'anl4_ebit_low / news_eod_close', 
    'anl4_ebit_low / news_eod_vwap', 
    'anl4_ebit_low / news_open', 
    'anl4_ebit_low / opt6_slcxp', 
    'anl4_ebit_low / pv13_revere_company_total', 
    'anl4_ebit_low / pv13_revere_index_value', 
    'anl4_ebit_low / pv13_revere_key_sector_total', 
    'anl4_ebit_low / pv13_revere_term_sector_total', 
    'anl4_ebit_low / rel_num_comp', 
    'anl4_ebit_low / rel_num_cust', 
    'anl4_ebit_low / rel_num_part', 
    'anl4_ebit_low / split', 
    'anl4_ebit_median / anl4_fcf_median', 
    'anl4_ebit_median / anl4_gric_high', 
    'anl4_ebit_median / anl4_ptp_low', 
    'anl4_ebit_median / anl4_ptp_median', 
    'anl4_ebit_median / anl4_ptpr_low', 
    'anl4_ebit_median / cashflow', 
    'anl4_ebit_median / fnd6_dcvt', 
    'anl4_ebit_median / fnd6_dd', 
    'anl4_ebit_median / fnd6_dltr', 
    'anl4_ebit_median / fnd6_dn', 
    'anl4_ebit_median / fnd6_dudd', 
    'anl4_ebit_median / fnd6_newqv1300_recdq', 
    'anl4_ebit_median / fnd6_rea', 
    'anl4_ebit_median / fnd6_recd', 
    'anl4_ebit_median / fscore_quality', 
    'anl4_ebit_median / mdl38_iv_div_payout_rate', 
    'anl4_ebit_median / star_val_earnings_projection_fy1', 
    'anl4_ebit_median / star_val_earnings_projection_fy4', 
    'anl4_ebit_median / star_val_earnings_projection_fy6', 
    'anl4_ebit_median / news_eod_close', 
    'anl4_ebit_median / opt6_slcxp', 
    'anl4_ebit_number / fnd6_recd', 
    'anl4_ebit_std / anl4_ebitda_low', 
    'anl4_ebit_std / anl4_fcf_low', 
    'anl4_ebit_std / anl4_ptp_low', 
    'anl4_ebit_std / fnd6_newqv1300_recdq', 
    'anl4_ebit_std / fnd6_pifo', 
    'anl4_ebit_std / fnd6_recd', 
    'anl4_ebit_value / anl4_ebitda_low', 
    'anl4_ebit_value / anl4_fcf_low', 
    'anl4_ebit_value / anl4_netprofit_low', 
    'anl4_ebit_value / anl4_ptp_low', 
    'anl4_ebit_value / anl4_ptpr_low', 
    'anl4_ebit_value / cashflow', 
    'anl4_ebit_value / debt', 
    'anl4_ebit_value / enterprise_value', 
    'anl4_ebit_value / fnd6_acqintan', 
    'anl4_ebit_value / fnd6_dcvt', 
    'anl4_ebit_value / fnd6_ds', 
    'anl4_ebit_value / fnd6_dudd', 
    'anl4_ebit_value / fnd6_newa2v1300_oiadp', 
    'anl4_ebit_value / fnd6_newa2v1300_oibdp', 
    'anl4_ebit_value / fnd6_newa2v1300_ppent', 
    'anl4_ebit_value / fnd6_newqv1300_lltq', 
    'anl4_ebit_value / fnd6_newqv1300_recdq', 
    'anl4_ebit_value / fnd6_recd', 
    'anl4_ebit_value / fnd6_txdbclq', 
    'anl4_ebit_value / fscore_quality', 
    'anl4_ebit_value / mdl38_iv_discount_rate', 
    'anl4_ebit_value / star_val_earnings_projection_fy1', 
    'anl4_ebit_value / star_val_earnings_projection_fy8', 
    'anl4_ebit_value / pv13_revere_term_sector_total', 
    'anl4_ebit_value / rel_num_part', 
    'anl4_ebitda_flag / fnd6_newa2v1300_ppent', 
    'anl4_ebitda_high / anl4_fcf_low', 
    'anl4_ebitda_high / anl4_gric_low', 
    'anl4_ebitda_high / anl4_netdebt_low', 
    'anl4_ebitda_high / anl4_netprofita_low', 
    'anl4_ebitda_high / anl4_ptp_low', 
    'anl4_ebitda_high / anl4_ptpr_low', 
    'anl4_ebitda_high / anl4_totassets_low', 
    'anl4_ebitda_high / est_ffo', 
    'anl4_ebitda_high / fn_op_lease_rent_exp_a', 
    'anl4_ebitda_high / fnd2_a_rvndm', 
    'anl4_ebitda_high / cashflow', 
    'anl4_ebitda_high / debt', 
    'anl4_ebitda_high / enterprise_value', 
    'anl4_ebitda_high / fnd6_beta', 
    'anl4_ebitda_high / fnd6_dcvt', 
    'anl4_ebitda_high / fnd6_dd', 
    'anl4_ebitda_high / fnd6_dd2', 
    'anl4_ebitda_high / fnd6_dd3', 
    'anl4_ebitda_high / fnd6_dd4', 
    'anl4_ebitda_high / fnd6_dd5', 
    'anl4_ebitda_high / fnd6_dltr', 
    'anl4_ebitda_high / fnd6_dn', 
    'anl4_ebitda_high / fnd6_ds', 
    'anl4_ebitda_high / fnd6_dudd', 
    'anl4_ebitda_high / fnd6_newa1v1300_gp', 
    'anl4_ebitda_high / fnd6_newa2v1300_oiadp', 
    'anl4_ebitda_high / fnd6_newa2v1300_oibdp', 
    'anl4_ebitda_high / fnd6_newa2v1300_ppent', 
    'anl4_ebitda_high / fnd6_newa2v1300_xsga', 
    'anl4_ebitda_high / fnd6_newqv1300_cshfdq', 
    'anl4_ebitda_high / fnd6_newqv1300_rcpq', 
    'anl4_ebitda_high / fnd6_newqv1300_recdq', 
    'anl4_ebitda_high / fnd6_newqv1300_spcep12', 
    'anl4_ebitda_high / fnd6_rea', 
    'anl4_ebitda_high / fnd6_recd', 
    'anl4_ebitda_high / fscore_quality', 
    'anl4_ebitda_high / mdl38_iv_discount_rate', 
    'anl4_ebitda_high / mdl38_iv_div_payout_rate', 
    'anl4_ebitda_high / mdl38_iv_growth_ear', 
    'anl4_ebitda_high / star_val_earnings_projection_fy1', 
    'anl4_ebitda_high / star_val_earnings_projection_fy10', 
    'anl4_ebitda_high / star_val_earnings_projection_fy11', 
    'anl4_ebitda_high / star_val_earnings_projection_fy12', 
    'anl4_ebitda_high / star_val_earnings_projection_fy13', 
    'anl4_ebitda_high / star_val_earnings_projection_fy14', 
    'anl4_ebitda_high / star_val_earnings_projection_fy15', 
    'anl4_ebitda_high / star_val_earnings_projection_fy2', 
    'anl4_ebitda_high / star_val_earnings_projection_fy3', 
    'anl4_ebitda_high / star_val_earnings_projection_fy4', 
    'anl4_ebitda_high / star_val_earnings_projection_fy5', 
    'anl4_ebitda_high / star_val_earnings_projection_fy6', 
    'anl4_ebitda_high / star_val_earnings_projection_fy7', 
    'anl4_ebitda_high / star_val_earnings_projection_fy8', 
    'anl4_ebitda_high / star_val_earnings_projection_fy9', 
    'anl4_ebitda_high / news_pe_ratio', 
    'anl4_ebitda_high / opt6_slcxp', 
    'anl4_ebitda_high / pv13_revere_company_total', 
    'anl4_ebitda_high / pv13_revere_index_value', 
    'anl4_ebitda_high / pv13_revere_term_sector_total', 
    'anl4_ebitda_high / rel_num_comp', 
    'anl4_ebitda_high / rel_num_cust', 
    'anl4_ebitda_high / rel_num_part', 
    'anl4_ebitda_high / split', 
    'anl4_ebitda_low / anl4_fcf_low', 
    'anl4_ebitda_low / anl4_gric_low', 
    'anl4_ebitda_low / anl4_netdebt_low', 
    'anl4_ebitda_low / anl4_netprofita_low', 
    'anl4_ebitda_low / anl4_ptp_low', 
    'anl4_ebitda_low / anl4_ptpr_low', 
    'anl4_ebitda_low / anl4_totassets_low', 
    'anl4_ebitda_low / est_ffo', 
    'anl4_ebitda_low / fn_op_lease_min_pay_due_in_3y_a', 
    'anl4_ebitda_low / fn_op_lease_rent_exp_a', 
    'anl4_ebitda_low / fnd2_a_rvndm', 
    'anl4_ebitda_low / fnd2_asdm', 
    'anl4_ebitda_low / cashflow', 
    'anl4_ebitda_low / debt', 
    'anl4_ebitda_low / enterprise_value', 
    'anl4_ebitda_low / fnd6_acqintan', 
    'anl4_ebitda_low / fnd6_aox', 
    'anl4_ebitda_low / fnd6_dcvsub', 
    'anl4_ebitda_low / fnd6_dcvt', 
    'anl4_ebitda_low / fnd6_dd', 
    'anl4_ebitda_low / fnd6_dd2', 
    'anl4_ebitda_low / fnd6_dd3', 
    'anl4_ebitda_low / fnd6_dd4', 
    'anl4_ebitda_low / fnd6_dd5', 
    'anl4_ebitda_low / fnd6_dltr', 
    'anl4_ebitda_low / fnd6_dn', 
    'anl4_ebitda_low / fnd6_ds', 
    'anl4_ebitda_low / fnd6_dudd', 
    'anl4_ebitda_low / fnd6_fopo', 
    'anl4_ebitda_low / fnd6_lcoxdr', 
    'anl4_ebitda_low / fnd6_newa1v1300_gp', 
    'anl4_ebitda_low / fnd6_newa2v1300_oiadp', 
    'anl4_ebitda_low / fnd6_newa2v1300_oibdp', 
    'anl4_ebitda_low / fnd6_newa2v1300_ppent', 
    'anl4_ebitda_low / fnd6_newa2v1300_xsga', 
    'anl4_ebitda_low / fnd6_newqv1300_lltq', 
    'anl4_ebitda_low / fnd6_newqv1300_rcpq', 
    'anl4_ebitda_low / fnd6_newqv1300_recdq', 
    'anl4_ebitda_low / fnd6_newqv1300_reunaq', 
    'anl4_ebitda_low / fnd6_optca', 
    'anl4_ebitda_low / fnd6_pifo', 
    'anl4_ebitda_low / fnd6_recd', 
    'anl4_ebitda_low / fnd6_xad', 
    'anl4_ebitda_low / fnd6_xrent', 
    'anl4_ebitda_low / sales_ps', 
    'anl4_ebitda_low / mdl38_iv_discount_rate', 
    'anl4_ebitda_low / mdl38_iv_div_payout_rate', 
    'anl4_ebitda_low / star_val_earnings_projection_fy1', 
    'anl4_ebitda_low / star_val_earnings_projection_fy10', 
    'anl4_ebitda_low / star_val_earnings_projection_fy11', 
    'anl4_ebitda_low / star_val_earnings_projection_fy12', 
    'anl4_ebitda_low / star_val_earnings_projection_fy13', 
    'anl4_ebitda_low / star_val_earnings_projection_fy14', 
    'anl4_ebitda_low / star_val_earnings_projection_fy15', 
    'anl4_ebitda_low / star_val_earnings_projection_fy2', 
    'anl4_ebitda_low / star_val_earnings_projection_fy3', 
    'anl4_ebitda_low / star_val_earnings_projection_fy4', 
    'anl4_ebitda_low / star_val_earnings_projection_fy5', 
    'anl4_ebitda_low / star_val_earnings_projection_fy6', 
    'anl4_ebitda_low / star_val_earnings_projection_fy7', 
    'anl4_ebitda_low / star_val_earnings_projection_fy8', 
    'anl4_ebitda_low / star_val_earnings_projection_fy9', 
    'anl4_ebitda_low / star_val_piv_ratio', 
    'anl4_ebitda_low / news_eod_close', 
    'anl4_ebitda_low / news_open', 
    'anl4_ebitda_low / pv13_revere_company_total', 
    'anl4_ebitda_low / pv13_revere_index_value', 
    'anl4_ebitda_low / pv13_revere_key_sector_total', 
    'anl4_ebitda_low / pv13_revere_term_sector_total', 
    'anl4_ebitda_low / rel_num_all', 
    'anl4_ebitda_low / rel_num_comp', 
    'anl4_ebitda_low / rel_num_cust', 
    'anl4_ebitda_low / rel_num_part', 
    'anl4_ebitda_low / split', 
    'anl4_ebitda_number / fnd6_recd', 
    'anl4_ebitda_std / anl4_fcf_low', 
    'anl4_ebitda_std / anl4_totassets_median', 
    'anl4_ebitda_std / enterprise_value', 
    'anl4_ebitda_std / fnd6_dcvt', 
    'anl4_ebitda_std / fnd6_newa2v1300_oibdp', 
    'anl4_ebitda_std / fnd6_newqv1300_recdq', 
    'anl4_ebitda_std / fnd6_pifo', 
    'anl4_ebitda_std / fnd6_recd', 
    'anl4_ebitda_std / opt6_slcxp', 
    'anl4_ebitda_std / pv13_revere_term_sector_total', 
    'anl4_ebitda_std / rel_num_part', 
    'anl4_ebitda_value / anl4_fcf_low', 
    'anl4_ebitda_value / anl4_medianepsbfam', 
    'anl4_ebitda_value / anl4_netdebt_low', 
    'anl4_ebitda_value / anl4_netprofit_low', 
    'anl4_ebitda_value / anl4_netprofita_low', 
    'anl4_ebitda_value / anl4_ptp_low', 
    'anl4_ebitda_value / anl4_ptpr_low', 
    'anl4_ebitda_value / anl4_rd_exp_low', 
    'anl4_ebitda_value / anl4_totassets_low', 
    'anl4_ebitda_value / est_ffo', 
    'anl4_ebitda_value / fn_op_lease_rent_exp_a', 
    'anl4_ebitda_value / fnd2_a_rvndm', 
    'anl4_ebitda_value / fnd2_oprlsfmpdcurr', 
    'anl4_ebitda_value / cashflow', 
    'anl4_ebitda_value / debt', 
    'anl4_ebitda_value / enterprise_value', 
    'anl4_ebitda_value / fnd6_dcvt', 
    'anl4_ebitda_value / fnd6_dd', 
    'anl4_ebitda_value / fnd6_dd3', 
    'anl4_ebitda_value / fnd6_dd4', 
    'anl4_ebitda_value / fnd6_dd5', 
    'anl4_ebitda_value / fnd6_ds', 
    'anl4_ebitda_value / fnd6_dudd', 
    'anl4_ebitda_value / fnd6_fatc', 
    'anl4_ebitda_value / fnd6_newa1v1300_cshfd', 
    'anl4_ebitda_value / fnd6_newa2v1300_oiadp', 
    'anl4_ebitda_value / fnd6_newa2v1300_oibdp', 
    'anl4_ebitda_value / fnd6_newa2v1300_ppent', 
    'anl4_ebitda_value / fnd6_newa2v1300_xsga', 
    'anl4_ebitda_value / fnd6_newqv1300_rcpq', 
    'anl4_ebitda_value / fnd6_newqv1300_recdq', 
    'anl4_ebitda_value / fnd6_optca', 
    'anl4_ebitda_value / fnd6_rea', 
    'anl4_ebitda_value / fnd6_recd', 
    'anl4_ebitda_value / fnd6_xad', 
    'anl4_ebitda_value / fscore_profitability', 
    'anl4_ebitda_value / fscore_quality', 
    'anl4_ebitda_value / mdl38_iv_discount_rate', 
    'anl4_ebitda_value / star_val_earnings_projection_fy1', 
    'anl4_ebitda_value / star_val_earnings_projection_fy13', 
    'anl4_ebitda_value / star_val_earnings_projection_fy8', 
    'anl4_ebitda_value / pv13_revere_term_sector_total', 
    'anl4_ebitda_value / rel_num_cust', 
    'anl4_ebitda_value / rel_num_part', 
    'anl4_epsr_flag / split', 
    'anl4_epsr_high / anl4_epsr_low', 
    'anl4_epsr_high / anl4_median_epsreported', 
    'anl4_epsr_low / anl4_median_epsreported', 
    'anl4_epsr_value / news_eod_close', 
    'anl4_epsr_value / news_pe_ratio', 
    'anl4_fcf_high / anl4_fcf_low', 
    'anl4_fcf_high / anl4_fcf_median', 
    'anl4_fcf_high / anl4_fcfps_median', 
    'anl4_fcf_high / anl4_gric_low', 
    'anl4_fcf_high / anl4_netprofit_low', 
    'anl4_fcf_high / anl4_ptp_low', 
    'anl4_fcf_high / fnd2_a_restructuringcharges', 
    'anl4_fcf_high / debt', 
    'anl4_fcf_high / enterprise_value', 
    'anl4_fcf_high / fnd6_beta', 
    'anl4_fcf_high / fnd6_dd2', 
    'anl4_fcf_high / fnd6_dd3', 
    'anl4_fcf_high / fnd6_dd5', 
    'anl4_fcf_high / fnd6_dltr', 
    'anl4_fcf_high / fnd6_dudd', 
    'anl4_fcf_high / fnd6_newa2v1300_ppent', 
    'anl4_fcf_high / fnd6_newqv1300_ivltq', 
    'anl4_fcf_high / fnd6_newqv1300_recdq', 
    'anl4_fcf_high / fnd6_rea', 
    'anl4_fcf_high / fnd6_recd', 
    'anl4_fcf_high / income', 
    'anl4_fcf_high / star_val_dividend_projection_fy1', 
    'anl4_fcf_high / star_val_earnings_projection_fy1', 
    'anl4_fcf_high / star_val_earnings_projection_fy10', 
    'anl4_fcf_high / star_val_earnings_projection_fy12', 
    'anl4_fcf_high / star_val_earnings_projection_fy13', 
    'anl4_fcf_high / star_val_earnings_projection_fy2', 
    'anl4_fcf_high / star_val_earnings_projection_fy4', 
    'anl4_fcf_high / star_val_earnings_projection_fy6', 
    'anl4_fcf_high / star_val_earnings_projection_fy7', 
    'anl4_fcf_high / star_val_earnings_projection_fy8', 
    'anl4_fcf_high / news_cap', 
    'anl4_fcf_high / news_open', 
    'anl4_fcf_high / opt6_slcxp', 
    'anl4_fcf_high / opt6_xpslcy1', 
    'anl4_fcf_high / pv13_revere_company_total', 
    'anl4_fcf_high / pv13_revere_index_value', 
    'anl4_fcf_high / pv13_revere_term_sector_total', 
    'anl4_fcf_high / rel_num_cust', 
    'anl4_fcf_low / anl4_gric_low', 
    'anl4_fcf_low / anl4_netprofit_low', 
    'anl4_fcf_low / anl4_netprofita_low', 
    'anl4_fcf_low / anl4_ptp_low', 
    'anl4_fcf_low / anl4_ptpr_low', 
    'anl4_fcf_low / cashflow', 
    'anl4_fcf_low / enterprise_value', 
    'anl4_fcf_low / fnd6_dd2', 
    'anl4_fcf_low / fnd6_dd3', 
    'anl4_fcf_low / fnd6_dd5', 
    'anl4_fcf_low / fnd6_dltr', 
    'anl4_fcf_low / fnd6_newa2v1300_oiadp', 
    'anl4_fcf_low / fnd6_newa2v1300_oibdp', 
    'anl4_fcf_low / fnd6_newqv1300_ivltq', 
    'anl4_fcf_low / fnd6_newqv1300_recdq', 
    'anl4_fcf_low / fnd6_rea', 
    'anl4_fcf_low / fnd6_recd', 
    'anl4_fcf_low / fnd6_xad', 
    'anl4_fcf_low / income', 
    'anl4_fcf_low / fscore_profitability', 
    'anl4_fcf_low / mdl38_iv_year_div', 
    'anl4_fcf_low / star_val_dividend_projection_fy1', 
    'anl4_fcf_low / star_val_dividend_projection_fy11', 
    'anl4_fcf_low / star_val_dividend_projection_fy4', 
    'anl4_fcf_low / star_val_dividend_projection_fy8', 
    'anl4_fcf_low / star_val_earnings_projection_fy1', 
    'anl4_fcf_low / star_val_earnings_projection_fy10', 
    'anl4_fcf_low / star_val_earnings_projection_fy11', 
    'anl4_fcf_low / star_val_earnings_projection_fy12', 
    'anl4_fcf_low / star_val_earnings_projection_fy13', 
    'anl4_fcf_low / star_val_earnings_projection_fy14', 
    'anl4_fcf_low / star_val_earnings_projection_fy15', 
    'anl4_fcf_low / star_val_earnings_projection_fy2', 
    'anl4_fcf_low / star_val_earnings_projection_fy3', 
    'anl4_fcf_low / star_val_earnings_projection_fy4', 
    'anl4_fcf_low / star_val_earnings_projection_fy5', 
    'anl4_fcf_low / star_val_earnings_projection_fy7', 
    'anl4_fcf_low / star_val_earnings_projection_fy8', 
    'anl4_fcf_low / star_val_earnings_projection_fy9', 
    'anl4_fcf_low / news_open', 
    'anl4_fcf_low / news_ton_last', 
    'anl4_fcf_low / opt6_divamt', 
    'anl4_fcf_low / opt6_iratelt', 
    'anl4_fcf_low / opt6_slcxp', 
    'anl4_fcf_low / pv13_revere_company_total', 
    'anl4_fcf_low / pv13_revere_key_sector_total', 
    'anl4_fcf_low / pv13_revere_term_sector_total', 
    'anl4_fcf_low / rel_num_comp', 
    'anl4_fcf_low / rel_num_cust', 
    'anl4_fcf_low / rel_num_part', 
    'anl4_fcf_low / dividend', 
    'anl4_fcf_low / sharesout', 
    'anl4_fcf_median / anl4_fcf_value', 
    'anl4_fcf_median / anl4_gric_low', 
    'anl4_fcf_median / anl4_netprofit_low', 
    'anl4_fcf_median / anl4_netprofit_median', 
    'anl4_fcf_median / anl4_netprofita_median', 
    'anl4_fcf_median / anl4_ptp_low', 
    'anl4_fcf_median / fnd2_oprlsfmpdcurr', 
    'anl4_fcf_median / cashflow', 
    'anl4_fcf_median / enterprise_value', 
    'anl4_fcf_median / fnd6_dcvt', 
    'anl4_fcf_median / fnd6_dd2', 
    'anl4_fcf_median / fnd6_dd5', 
    'anl4_fcf_median / fnd6_newa1v1300_cshfd', 
    'anl4_fcf_median / fnd6_newa1v1300_dvc', 
    'anl4_fcf_median / fnd6_newa2v1300_oiadp', 
    'anl4_fcf_median / fnd6_newqv1300_recdq', 
    'anl4_fcf_median / fnd6_rea', 
    'anl4_fcf_median / fnd6_recd', 
    'anl4_fcf_median / fscore_profitability', 
    'anl4_fcf_median / mdl38_iv_discount_rate', 
    'anl4_fcf_median / mdl38_iv_div_payout_rate', 
    'anl4_fcf_median / mdl38_iv_year_div', 
    'anl4_fcf_median / star_val_dividend_projection_fy1', 
    'anl4_fcf_median / star_val_dividend_projection_fy2', 
    'anl4_fcf_median / star_val_earnings_projection_fy1', 
    'anl4_fcf_median / star_val_earnings_projection_fy10', 
    'anl4_fcf_median / star_val_earnings_projection_fy11', 
    'anl4_fcf_median / star_val_earnings_projection_fy13', 
    'anl4_fcf_median / star_val_earnings_projection_fy2', 
    'anl4_fcf_median / star_val_earnings_projection_fy3', 
    'anl4_fcf_median / star_val_earnings_projection_fy4', 
    'anl4_fcf_median / star_val_earnings_projection_fy6', 
    'anl4_fcf_median / star_val_earnings_projection_fy7', 
    'anl4_fcf_median / star_val_earnings_projection_fy8', 
    'anl4_fcf_median / star_val_earnings_projection_fy9', 
    'anl4_fcf_median / news_cap', 
    'anl4_fcf_median / news_open', 
    'anl4_fcf_median / opt6_iratelt', 
    'anl4_fcf_median / opt6_xpslcm1', 
    'anl4_fcf_median / pv13_revere_index_cap', 
    'anl4_fcf_median / rel_num_cust', 
    'anl4_fcf_median / rel_num_part', 
    'anl4_fcf_median / dividend', 
    'anl4_fcf_number / fnd6_recd', 
    "ebit /assets", # 资产息税前利润率，衡量企业运用全部资产获取利润的能力
    "income /equity", # 净资产收益率，反映股东权益的收益水平
    "cashflow_op /liabilities", # 经营活动现金流量对负债的保障程度
    "ebitda /interest_expense", # 利息保障倍数，衡量企业支付负债利息的能力
    "sales /inventory", # 存货周转率，反映存货的周转速度
    "operating_income /revenue", # 营业利润率，体现企业经营活动的盈利能力
    "net_income /assets", # 资产净利率，反映资产利用的综合效果
    "receivable /sales", # 应收账款周转率，反映应收账款周转速度
    "working_capital /current_liabilities", # 营运资本对流动负债的保障程度
    "capex /assets", # 资本支出占资产的比例，反映企业的投资力度
    "debt /equity", # 资产负债率，衡量企业长期偿债能力
    "income_tax /pretax_income", # 税负率，反映企业所承担的税收负担
    "rd_expense /revenue", # 研发投入占营收的比例，体现企业对研发的重视程度
    "sga_expense /sales", # 销售及管理费用占销售额的比例，反映企业运营成本控制情况
    "inventory_turnover * 365 /inventory", # 存货周转天数，衡量存货的变现速度
    "return_assets * assets /equity", # 从资产回报率推导权益回报率的一种变形
    "return_equity * equity /assets", # 从权益回报率推导资产回报率的一种变形
    "operating_expense /revenue", # 营业成本率，衡量企业经营成本在营收中的占比
    "liabilities_curr /assets_curr", # 流动比率，衡量企业短期偿债能力
    "pretax_income /invested_capital", # 投资回报率，反映投入资本的获利能力
    "goodwill /assets", # 商誉占资产的比例，反映企业商誉在总资产中的权重
    "sales_growth /sales", # 销售增长率，衡量企业销售的增长情况
    "sales_ps * fnd6_csho /sales", # 从每股销售额和总股数推导总销售额的一种变形
    "ppent /assets", # 固定资产净值占资产的比例，反映企业固定资产的规模
    "interest_expense /debt", # 债务的利息率，反映企业债务融资的成本
    "retained_earnings /equity", # 留存收益率，反映企业利润留存的比例
    "income_beforeextra /assets", # 剔除特殊项目前的资产收益率，衡量企业正常经营的盈利能力
    "cash /liabilities", # 现金对负债的覆盖程度，反映企业即时偿债能力
    "capex /sales", # 资本支出占销售额的比例，反映企业对未来发展的投资力度
    "inventory /current_assets", # 存货占流动资产的比例，反映企业流动资产的结构
    "net_income /invested_capital", # 投资净利率，衡量投入资本获取净收益的能力
    "return_assets /return_equity", # 资产回报率与权益回报率的比值，反映权益乘数对回报率的影响
    "operating_income /operating_expense", # 营业利润与营业成本的比值，衡量企业经营效益
    "liabilities /assets", # 资产负债率的另一种表达，衡量企业的负债水平
    "ebit /interest_expense", # 息税前利润对利息的保障倍数，衡量企业支付利息的能力
    "income /revenue", # 销售净利率，反映企业销售收入的收益水平
    "receivable /current_assets", # 应收账款占流动资产的比例，反映流动资产的质量
    "working_capital /assets", # 营运资本占资产的比例，反映企业资产的流动性和偿债能力
    "capex /operating_cashflow", # 资本支出与经营活动现金流量的比例，反映企业现金流量对投资的支持能力
    "debt /assets", # 资产负债率的另一种表达，衡量企业的负债程度
    "income_tax /income", # 净利润的税负率，反映企业净利润所承担的税收负担
    "rd_expense /operating_income", # 研发投入对营业利润的占比，反映企业在盈利基础上的研发投入情况
    "sga_expense /operating_income", # 销售及管理费用对营业利润的占比，反映运营成本对利润的影响
    "inventory_turnover /liabilities_curr", # 存货周转率与流动负债的关系，从存货周转角度看对流动负债的影响
    "return_equity /return_assets", # 权益回报率与资产回报率的比值，反映权益杠杆的作用
    "operating_expense /operating_income", # 营业成本对营业利润的覆盖倍数，衡量企业盈利空间
    "liabilities_curr /current_ratio", # 流动负债与流动比率的关系，从比率角度看流动负债情况
    "pretax_income /assets", # 税前资产收益率，衡量企业在税前的资产获利能力
    "goodwill /equity", # 商誉占股东权益的比例，反映商誉对股东权益的影响
    "sales_growth /invested_capital", # 销售增长率与投入资本的关系，反映投入资本对销售增长的推动作用
    "sales_ps /earnings_per_share", # 每股销售额与每股收益的关系，反映企业每股的经营和盈利情况
    "ppent /liabilities", # 固定资产净值对负债的比例，反映固定资产对负债的保障程度
    "interest_expense /operating_income", # 利息费用对营业利润的占比，反映利息负担对企业盈利的影响
    "retained_earnings /assets", # 留存收益占资产的比例，反映企业资产中留存收益的构成
    "income_beforeextra /equity", # 剔除特殊项目前的净资产收益率，衡量企业正常经营的股东权益收益水平
    "cash /current_liabilities", # 现金对流动负债的保障程度，反映企业短期偿债的即时能力
    "capex /net_income", # 资本支出与净利润的比例，反映企业用净利润进行投资的能力
    "inventory /liabilities", # 存货对负债的比例，反映存货作为偿债资源的能力
    "net_income /operating_income", # 净利润与营业利润的比值，反映企业的盈利质量
    "return_assets * equity /assets", # 从资产回报率推导权益相关指标的一种变形
    "operating_income /liabilities", # 营业利润对负债的比例，反映企业营业利润对负债的覆盖能力
    "liabilities /equity", # 负债权益比，衡量企业财务杠杆的大小
    "ebit /assets_curr", # 流动资产的息税前利润率，衡量流动资产的获利能力
    "income /assets_curr", # 流动资产收益率，反映流动资产的收益水平
    "cashflow_op /assets", # 经营活动现金流量对资产的比例，反映资产产生现金流量的能力
    "ebitda /assets", # 资产息税折旧摊销前利润率，衡量企业资产在未扣除折旧摊销前的盈利能力
    "sales /receivable", # 应收账款回收期的倒数，反映应收账款回收速度
    "working_capital /revenue", # 营运资本对营收的比例，反映营运资本对业务的支持程度
    "capex /liabilities_curr", # 资本支出对流动负债的比例，反映流动负债对资本支出的支持能力
    "debt /assets_curr", # 流动资产的资产负债率，衡量流动资产的负债水平
    "income_tax /operating_income", # 营业利润的税负率，反映营业利润所承担的税收负担
    "rd_expense /pretax_income", # 研发投入对税前利润的占比，反映企业在税前利润基础上的研发投入情况
    "sga_expense /pretax_income", # 销售及管理费用对税前利润的占比，反映运营成本对税前利润的影响
    "inventory_turnover * 365 /sales", # 存货周转天数的另一种计算方式，衡量存货变现速度
    "return_equity * assets /equity", # 从权益回报率推导资产相关指标的一种变形
    "operating_expense /liabilities", # 营业成本对负债的比例，反映企业营业成本与负债的关系
    "liabilities_curr /liabilities", # 流动负债占总负债的比例，反映企业负债的结构
    "pretax_income /equity", # 税前净资产收益率，衡量企业在税前的股东权益收益水平
    "goodwill /liabilities", # 商誉对负债的比例，反映商誉在企业负债背景下的相对规模
    "sales_growth /assets", # 销售增长率对资产的比例，反映资产对销售增长的支持能力
    "sales_ps * fnd6_csho /invested_capital", # 从每股销售额和总股数与投入资本的关系，反映投入资本的产出情况
    "ppent /equity", # 固定资产净值对股东权益的比例，反映固定资产对股东权益的贡献
    "interest_expense /pretax_income", # 利息费用对税前利润的占比，反映利息负担对税前利润的影响
    "retained_earnings /liabilities", # 留存收益对负债的比例，反映留存收益对负债的偿还能力
    "income_beforeextra /assets_curr", # 剔除特殊项目前的流动资产收益率，衡量企业正常经营的流动资产获利能力
    "cash /assets", # 现金占资产的比例，反映企业资产的流动性
    "capex /income", # 资本支出对净利润的比例，反映企业用盈利进行投资的情况
    "inventory /working_capital", # 存货对营运资本的比例，反映存货在营运资本中的占比
    "net_income /liabilities", # 净利润对负债的比例，反映企业净利润对负债的偿还能力
    "return_assets * liabilities /assets", # 从资产回报率推导负债相关指标的一种变形
    "operating_income /assets_curr", # 流动资产的营业利润率，衡量流动资产的经营效益
    "liabilities /assets_curr", # 流动资产的负债比率，衡量流动资产的负债程度
    "ebit /liabilities_curr", # 流动负债的息税前利润率，衡量流动负债的获利能力
    "income /liabilities_curr", # 流动负债的收益率，反映流动负债的收益水平
    "cashflow_op /assets_curr", # 经营活动现金流量对流动资产的比例，反映流动资产产生现金流量的能力
    "ebitda /liabilities_curr", # 流动负债的息税折旧摊销前利润率，衡量流动负债在未扣除折旧摊销前的盈利能力
    "sales /working_capital", # 营运资本周转率，反映营运资本的利用效率
    "capex /operating_income", # 资本支出对营业利润的比例，反映营业利润对资本支出的支持能力
    "debt /liabilities_curr", # 流动负债中债务的比例，反映流动负债的构成
    "income_tax /net_income", # 净利润的实际税负率，反映企业净利润的税收负担
    "rd_expense /sales_growth", # 研发投入对销售增长的比例，反映研发投入对销售增长的推动作用
    "sga_expense /sales_growth", # 销售及管理费用对销售增长的比例，反映运营成本对销售增长的影响
    "inventory_turnover * 365 /liabilities", # 存货周转天数与负债的关系，从存货周转角度看对负债的影响
    "return_equity * liabilities /equity", # 从权益回报率推导负债相关指标的一种变形
    "operating_expense /assets_curr", # 流动资产的营业成本率，衡量流动资产的成本水平
    "liabilities_curr /working_capital", # 流动负债对营运资本的比例，反映流动负债与营运资本的关系
    "pretax_income /assets_curr", # 税前流动资产收益率，衡量企业在税前的流动资产获利能力
    "goodwill /assets_curr", # 商誉对流动资产的比例，反映商誉在流动资产中的占比
    "sales_growth /liabilities_curr", # 销售增长率对流动负债的比例，反映流动负债对销售增长的支持能力
    "sales_ps * fnd6_csho /liabilities", # 从每股销售额和总股数与负债的关系，反映负债的产出情况
    "ppent /liabilities_curr", # 固定资产净值对流动负债的比例，反映固定资产对流动负债的保障程度
    "interest_expense /net_income", # 利息费用对净利润的占比，反映利息负担对净利润的影响
    "retained_earnings /assets_curr", # 留存收益对流动资产的比例，反映留存收益在流动资产中的构成
    "income_beforeextra /liabilities_curr", # 剔除特殊项目前的流动负债收益率，衡量企业正常经营的流动负债获利能力
    "cash /working_capital", # 现金对营运资本的比例，反映现金在营运资本中的占比
    "capex /cashflow_op", # 资本支出对经营活动现金流量的比例，反映经营活动现金流量对资本支出的支持能力
    "inventory /current_ratio", # 存货与流动比率的关系，从存货角度看流动比率情况
    "net_income /assets_curr", # 流动资产净利率，反映流动资产的综合收益能力
    "return_assets * working_capital /assets", # 从资产回报率推导营运资本相关指标的一种变形
    "operating_income /working_capital", # 营运资本的营业利润率，衡量营运资本的经营效益
    "liabilities /working_capital", # 营运资本的负债比率，衡量营运资本的负债程度
    "ebit /working_capital", # 营运资本的息税前利润率，衡量营运资本的获利能力
    "income /working_capital", # 营运资本的收益率，反映营运资本的收益水平
    "cashflow_op /working_capital", # 经营活动现金流量对营运资本的比例，反映营运资本产生现金流量的能力
    "ebitda /working_capital", # 营运资本的息税折旧摊销前利润率，衡量营运资本在未扣除折旧摊销前的盈利能力
    "sales /current_ratio", # 销售额与流动比率的关系，从销售角度看流动比率情况
    "capex /income_tax", # 资本支出对所得税的比例，反映所得税对资本支出的影响
    "debt /working_capital", # 营运资本中债务的比例，反映营运资本的构成
    "income_tax /cashflow_op", # 经营活动现金流量的税负率，反映经营活动现金流量所承担的税收负担
    "rd_expense /operating_expense", # 研发投入对营业成本的占比，反映营业成本中研发投入的情况
    "sga_expense /operating_expense", # 销售及管理费用对营业成本的占比，反映营业成本中运营成本的情况
    "inventory_turnover * 365 /working_capital", # 存货周转天数与营运资本的关系，从存货周转角度看对营运资本的影响
    "return_equity * working_capital /equity", # 从权益回报率推导营运资本相关指标的一种变形
    "operating_expense /working_capital", # 营运资本的营业成本率，衡量营运资本的成本水平
    "liabilities_curr /current_ratio * current_assets", # 从流动比率和流动资产推导流动负债的一种变形
    "pretax_income /working_capital", # 税前营运资本收益率，衡量企业在税前的营运资本获利能力
    "goodwill /working_capital", # 商誉对营运资本的比例，反映商誉在营运资本中的占比
    "sales_growth /working_capital", # 销售增长率对营运资本的比例，反映营运资本对销售增长的支持能力
    "sales_ps * fnd6_csho /working_capital", # 从每股销售额和总股数与营运资本的关系，反映营运资本的产出情况
    "ppent /working_capital", # 固定资产净值对营运资本的比例，反映固定资产对营运资本的贡献
    "interest_expense /cashflow_op", # 利息费用对经营活动现金流量的占比，反映利息负担对经营活动现金流量的影响
    "retained_earnings /working_capital", # 留存收益对营运资本的比例，反映留存收益在营运资本中的构成
    "income_beforeextra /working_capital", # 剔除特殊项目前的营运资本收益率，衡量企业正常经营的营运资本获利能力
    "cash /current_ratio * current_assets", # 从流动比率和流动资产推导现金的一种变形
    "capex /net_cashflow", # 资本支出对净现金流量（假设存在相关计算或数据）的比例，反映净现金流量对资本支出的支持能力
    "inventory /operating_income", # 存货对营业利润的比例，反映存货对营业利润的影响
    "net_income /working_capital", # 营运资本的净利润率，反映营运资本的盈利水平
    "return_assets * current_assets /assets", # 从资产回报率推导流动资产相关指标的一种变形
    "operating_income /current_assets", # 流动资产的营业利润率，衡量流动资产的经营效益
    "liabilities /current_assets", # 流动资产的负债比率，衡量流动资产的负债程度
    "anl4_adjusted_netincome_ft / anl4_totassets_value",
    "anl4_ebit / anl4_totassets_value",
    "anl4_netprofit_value / anl4_totassets_value",
    "anl4_fcf_value / anl4_totassets_value",
    "subtract(anl4_totassets_value, anl4_netdebt_mean)",
    "divide(anl4_adjusted_netincome_ft, est_bookvalue_ps)",
    "anl4_ebitda / anl4_totassets_value",
    "anl4_cfo_value / anl4_totassets_value",
    "anl4_netprofita_value / anl4_totassets_value",
    "divide(anl4_adjusted_netincome_ft, est_eps)",
    "anl4_adjusted_netincome_ft / est_ebitda",
    "anl4_ebit / est_ebitda",
    "anl4_netprofit_value / est_ebitda",
    "anl4_fcf_value / est_ebitda",
    "anl4_cfo_value / est_ebitda",
    "anl4_adjusted_netincome_ft / est_epsr",
    "anl4_ebit / est_epsr",
    "anl4_netprofit_value / est_epsr",
    "anl4_fcf_value / est_epsr",
    "anl4_cfo_value / est_epsr",
    "anl4_adjusted_netincome_ft / est_netprofit",
    "anl4_ebit / est_netprofit",
    "anl4_netprofit_value / est_netprofit",
    "anl4_fcf_value / est_netprofit",
    "anl4_cfo_value / est_netprofit",
    "anl4_adjusted_netincome_ft / est_netprofit_adj",
    "anl4_ebit / est_netprofit_adj",
    "anl4_netprofit_value / est_netprofit_adj",
    "anl4_fcf_value / est_netprofit_adj",
    "anl4_cfo_value / est_netprofit_adj",
    "anl4_adjusted_netincome_ft / est_cashflow_fin",
    "anl4_ebit / est_cashflow_fin",
    "anl4_netprofit_value / est_cashflow_fin",
    "anl4_fcf_value / est_cashflow_fin",
    "anl4_cfo_value / est_cashflow_fin",
    "anl4_adjusted_netincome_ft / est_cashflow_invst",
    "anl4_ebit / est_cashflow_invst",
    "anl4_netprofit_value / est_cashflow_invst",
    "anl4_fcf_value / est_cashflow_invst",
    "anl4_cfo_value / est_cashflow_invst",
    "anl4_adjusted_netincome_ft / est_cashflow_op",
    "anl4_ebit / est_cashflow_op",
    "anl4_netprofit_value / est_cashflow_op",
    "anl4_fcf_value / est_cashflow_op",
    "anl4_cfo_value / est_cashflow_op",
    "anl4_adjusted_netincome_ft / est_cashflow_ps",
    "anl4_ebit / est_cashflow_ps",
    "anl4_netprofit_value / est_cashflow_ps",
    "anl4_fcf_value / est_cashflow_ps",
    "anl4_cfo_value / est_cashflow_ps",
    "anl4_adjusted_netincome_ft / est_dividend_ps",
    "anl4_ebit / est_dividend_ps",
    "anl4_netprofit_value / est_dividend_ps",
    "anl4_fcf_value / est_dividend_ps",
    "anl4_cfo_value / est_dividend_ps",
    "anl4_adjusted_netincome_ft / est_ptp",
    "anl4_ebit / est_ptp",
    "anl4_netprofit_value / est_ptp",
    "anl4_fcf_value / est_ptp",
    "anl4_cfo_value / est_ptp",
    "anl4_adjusted_netincome_ft / est_ptpr",
    "anl4_ebit / est_ptpr",
    "anl4_netprofit_value / est_ptpr",
    "anl4_fcf_value / est_ptpr",
    "anl4_cfo_value / est_ptpr",
    "anl4_adjusted_netincome_ft / est_rd_expense",
    "anl4_ebit / est_rd_expense",
    "anl4_netprofit_value / est_rd_expense",
    "anl4_fcf_value / est_rd_expense",
    "anl4_cfo_value / est_rd_expense",
    "anl4_adjusted_netincome_ft / est_sales",
    "anl4_ebit / est_sales",
    "anl4_netprofit_value / est_sales",
    "anl4_fcf_value / est_sales",
    "anl4_cfo_value / est_sales",
    "anl4_adjusted_netincome_ft / est_sga",
    "anl4_ebit / est_sga",
    "anl4_netprofit_value / est_sga",
    "anl4_fcf_value / est_sga",
    "anl4_cfo_value / est_sga",
    "anl4_adjusted_netincome_ft / est_shequity",
    "anl4_ebit / est_shequity",
    "anl4_netprofit_value / est_shequity",
    "anl4_fcf_value / est_shequity",
    "anl4_cfo_value / est_shequity",
    "anl4_adjusted_netincome_ft / est_tbv_ps",
    "anl4_ebit / est_tbv_ps",
    "anl4_netprofit_value / est_tbv_ps",
    "anl4_fcf_value / est_tbv_ps",
    "anl4_cfo_value / est_tbv_ps",
    "anl4_adjusted_netincome_ft / est_tot_assets",
    "anl4_ebit / est_tot_assets",
    "anl4_netprofit_value / est_tot_assets",
    "anl4_fcf_value / est_tot_assets",
    "anl4_cfo_value / est_tot_assets",
    "anl4_adjusted_netincome_ft / est_tot_goodwill",
    "anl4_ebit / est_tot_goodwill",
    "anl4_netprofit_value / est_tot_goodwill",
    "anl4_fcf_value / est_tot_goodwill",
    "anl4_cfo_value / est_tot_goodwill", 
    "fn_profit_loss_a /fn_assets_fair_val_a", # 反映资产盈利能力，净利润与资产公允价值的比率
    "fn_income_from_equity_investments_a /fn_assets_fair_val_a", # 反映来自权益投资的收益占资产的比例
    "fn_comp_options_out_intrinsic_value_a /fn_comp_options_out_number_a", # 反映每份期权的平均内在价值
    "fn_amortization_of_intangible_assets_a /fn_finite_lived_intangible_assets_gross_a", # 反映无形资产的摊销比例
    "fn_liab_fair_val_a /fn_assets_fair_val_a", # 反映负债与资产的比例，衡量偿债能力
    "fn_def_tax_liab_a /fn_def_tax_assets_net_a", # 反映递延所得税负债与递延所得税资产净额的比例
    "fn_derivative_fair_value_of_derivative_asset_a /fn_derivative_fair_value_of_derivative_liability_a", # 反映衍生资产与衍生负债的公允价值比例
    "fn_income_tax_expense_a /fn_profit_loss_a", # 反映所得税费用占净利润的比例
    "fn_interest_paid_net_a /fn_debt_instrument_carrying_amount_a", # 反映债务的利息支付水平
    "fn_op_lease_rent_exp_a /fn_ppne_gross_a", # 反映经营租赁租金费用占固定资产原值的比例
    "fn_proceeds_from_issuance_of_common_stock_a /fn_entity_common_stock_shares_out_a", # 反映每股发行普通股所获得的现金流入
    "fn_repayments_of_debt_a /fn_proceeds_from_issuance_of_debt_a", # 反映债务偿还与发行债务所得的比例
    "fn_taxes_payable_a /fn_employee_related_liab_a", # 反映应付税款占员工相关负债的比例
    "fn_unrecognized_tax_benefits_a /fn_def_tax_assets_net_a", # 反映未确认税收利益与递延所得税资产净额的比例
    "fn_accum_oth_income_loss_net_of_tax_a /fn_profit_loss_a", # 反映其他综合收益净额占净利润的比例
    "fn_business_combination_purchase_price_a /fn_assets_fair_val_a", # 反映企业合并购买价格与资产公允价值的比例
    "fn_comp_non_opt_vested_a /fn_comp_non_opt_grants_a", # 反映非期权类权益支付工具的授予与归属比例
    "fn_debt_instrument_interest_rate_stated_percentage_a /fn_debt_instrument_carrying_amount_a", # 反映债务的实际利率水平
    "fn_eff_income_tax_rate_continuing_operations_a /fn_income_tax_expense_a", # 反映有效所得税税率与所得税费用的关系
    "fn_finite_lived_intangible_assets_net_a /fn_assets_fair_val_a", # 反映有限寿命无形资产净额占资产公允价值的比例
    "fn_goodwill_acquired_during_period_a /fn_assets_fair_val_a", # 反映当期获得的商誉占资产公允价值的比例
    "fn_incremental_shares_attributable_to_share_based_payment_a /fn_entity_common_stock_shares_out_a", # 反映基于股份支付的增量股份占普通股流通股的比例
    "fn_intangible_assets_accum_amort_a /fn_finite_lived_intangible_assets_gross_a", # 反映无形资产累计摊销占原值的比例
    "fn_line_of_credit_facility_amount_out_a /fn_line_of_credit_facility_max_borrowing_capacity_a", # 反映信用额度的使用比例
    "fn_mne_a /fn_assets_fair_val_a", # 反映机器设备等资产占总资产的比例
    "fn_new_shares_issued_a /fn_entity_common_stock_shares_out_a", # 反映新发行股份占流通股的比例
    "fn_op_lease_min_pay_due_a /fn_liab_fair_val_a", # 反映经营租赁最低付款额占负债公允价值的比例
    "fn_oth_income_loss_net_of_tax_a /fn_profit_loss_a", # 反映其他综合收益净额占净利润的比例
    "fn_payments_for_repurchase_of_common_stock_a /fn_proceeds_from_issuance_of_common_stock_a", # 反映普通股回购支付与发行所得的比例
    "fn_ppne_gross_a /fn_assets_fair_val_a", # 反映固定资产原值占资产公允价值的比例
    "fn_prepaid_expense_a /fn_assets_fair_val_a", # 反映预付费用占资产公允价值的比例
    "fn_repurchased_shares_a /fn_entity_common_stock_shares_out_a", # 反映回购股份占流通股的比例
    "subtract (fn_assets_fair_val_a, fn_liab_fair_val_a)", # 反映净资产，资产减去负债
    "divide (fn_profit_loss_a, fn_avg_diluted_sharesout_adj_a)", # 每股收益，净利润除以稀释后平均流通股数
    "divide (fn_income_from_equity_investments_a, fn_entity_common_stock_shares_out_a)", # 每股权益投资收益
    "divide (fn_comp_options_out_intrinsic_value_a, fn_comp_options_out_weighted_avg_a)", # 基于期权加权平均价格的内在价值比例
    "divide (fn_amortization_of_intangible_assets_a, fn_finite_lived_intangible_assets_net_a)", # 基于无形资产净值的摊销比例
    "divide (fn_liab_fair_val_a, fn_assets_fair_val_l1_a)", # 负债公允价值与一级资产公允价值的比例
    "divide (fn_def_tax_liab_a, fn_def_tax_assets_liab_net_a)", # 递延所得税负债与递延所得税资产负债净额的比例
    "divide (fn_derivative_fair_value_of_derivative_asset_a, fn_derivative_notional_amount_a)", # 衍生资产公允价值与名义金额的比例
    "divide (fn_income_tax_expense_a, fn_income_from_equity_investments_a)", # 权益投资收益的所得税费用比例
    "divide (fn_interest_paid_net_a, fn_interest_payable_a)", # 已支付利息与应付利息的比例
    "divide (fn_op_lease_rent_exp_a, fn_op_lease_min_pay_due_a)", # 经营租赁租金费用与最低付款额的比例
    "divide (fn_proceeds_from_issuance_of_common_stock_a, fn_new_shares_issued_a)", # 每股新发行普通股的筹资额
    "divide (fn_repayments_of_debt_a, fn_debt_instrument_carrying_amount_a)", # 债务偿还与债务账面价值的比例
    "divide (fn_taxes_payable_a, fn_profit_loss_a)", # 应付税款占净利润的比例
    "divide (fn_unrecognized_tax_benefits_a, fn_def_tax_liab_a)", # 未确认税收利益与递延所得税负债的比例
    "divide (fn_accum_oth_income_loss_fx_adj_net_of_tax_a, fn_profit_loss_a)", # 外汇调整的其他综合收益净额占净利润的比例
    "divide (fn_business_combination_assets_aquired_goodwill_a, fn_business_combination_purchase_price_a)", # 企业合并中商誉占购买价格的比例
    "divide (fn_comp_non_opt_nonvested_number_a, fn_comp_non_opt_grants_a)", # 非期权类未归属权益工具数量与授予数量的比例
    "divide (fn_debt_instrument_face_amount_a, fn_debt_instrument_carrying_amount_a)", # 债务面值与账面价值的比例
    "divide (fn_eff_income_tax_rate_continuing_operations_a, fn_income_tax_expense_a)", # 有效所得税税率与所得税费用的比例（重复但从不同角度理解）
    "divide (fn_finite_lived_intangible_assets_acq_a, fn_assets_fair_val_a)", # 当期收购的有限寿命无形资产占资产公允价值的比例
    "divide (fn_goodwill_acquired_during_period_a, fn_business_combination_purchase_price_a)", # 企业合并中当期获得商誉占购买价格的比例
    "divide (fn_incremental_shares_attributable_to_share_based_payment_a, fn_avg_diluted_sharesout_adj_a)", # 基于股份支付的增量股份占稀释后平均流通股数的比例
    "divide (fn_intangible_assets_accum_amort_a, fn_finite_lived_intangible_assets_acq_a)", # 无形资产累计摊销与当期收购无形资产的比例
    "divide (fn_line_of_credit_facility_amount_out_a, fn_liab_fair_val_a)", # 信用额度使用金额占负债公允价值的比例
    "divide (fn_mne_a, fn_ppne_gross_a)", # 机器设备等资产占固定资产原值的比例
    "divide (fn_new_shares_options_a, fn_entity_common_stock_shares_out_a)", # 新行使的股份期权占流通股的比例
    "divide (fn_op_lease_min_pay_due_in_2y_a, fn_op_lease_min_pay_due_a)", # 未来第二年经营租赁最低付款额占总最低付款额的比例
    "divide (fn_oth_income_loss_available_for_sale_securities_adj_of_tax_a, fn_profit_loss_a)", # 可供出售证券调整的其他综合收益净额占净利润的比例
    "divide (fn_payments_to_acquire_businesses_net_of_cash_acquired_a, fn_assets_fair_val_a)", # 企业收购净现金流出占资产公允价值的比例
    "divide (fn_ppne_gross_a, fn_liab_fair_val_a)", # 固定资产原值与负债公允价值的比例
    "divide (fn_prepaid_expense_a, fn_liab_fair_val_a)", # 预付费用与负债公允价值的比例
    "divide (fn_repurchased_shares_value_a, fn_proceeds_from_issuance_of_common_stock_a)", # 回购股份价值与发行普通股所得的比例
    "subtract (fn_assets_fair_val_l1_a, fn_assets_fair_val_l2_a)", # 一级资产公允价值减去二级资产公允价值
    "add (fn_liab_fair_val_l1_a, fn_liab_fair_val_l2_a)", # 一级负债公允价值加上二级负债公允价值
    "multiply (fn_profit_loss_a, 100 /fn_assets_fair_val_a)", # 资产利润率，净利润乘以 100 再除以资产公允价值
    "log (fn_assets_fair_val_a)", # 资产公允价值的对数
    "power (fn_income_from_equity_investments_a, 2)", # 权益投资收益的平方
    "signed_power (fn_comp_options_out_intrinsic_value_a, 0.5)", # 期权内在价值的 0.5 次方
    "abs (subtract (fn_derivative_fair_value_of_derivative_asset_a, fn_derivative_fair_value_of_derivative_liability_a))", # 衍生资产与衍生负债公允价值差值的绝对值
    "ts_mean (fn_profit_loss_a, d=12)", # 过去 12 期净利润的时间序列均值
    "ts_std_dev (fn_income_tax_expense_a, d=6)", # 过去 6 期所得税费用的时间序列标准差
    "ts_corr (fn_profit_loss_a, fn_assets_fair_val_a, d=10)", # 过去 10 期净利润与资产公允价值的时间序列相关性
    "group_mean (fn_profit_loss_a, weight=1, group='industry')", # 按行业分组的净利润均值
    "group_zscore (fn_liab_fair_val_a, group='size')", # 按规模分组的负债公允价值的 z 分数
    "scale (fn_income_from_equity_investments_a, scale=100)", # 权益投资收益缩放 100 倍
    "winsorize (fn_derivative_fair_value_of_derivative_asset_a, std=3)", # 对衍生资产公允价值进行缩尾处理
    "vec_sum (fn_assets_fair_val_l1_a, fn_assets_fair_val_l2_a, fn_assets_fair_val_l3_a)", # 一级、二级、三级资产公允价值的向量和
    "vec_avg (fn_liab_fair_val_l1_a, fn_liab_fair_val_l2_a, fn_liab_fair_val_l3_a)", # 一级、二级、三级负债公允价值的向量均值
    "bucket (rank (fn_profit_loss_a, rate=2), range='0, 1, 0.1')", # 对净利润进行排名并分桶
    "if_else (greater (fn_profit_loss_a, 0), 1, -1)", # 判断净利润是否大于 0，大于为 1，否则为 - 1
    "and (greater (fn_profit_loss_a, 0), less (fn_liab_fair_val_a, fn_assets_fair_val_a))", # 判断净利润大于 0 且负债小于资产
    "or (greater (fn_income_from_equity_investments_a, 0), greater (fn_comp_options_out_intrinsic_value_a, 0))" # 判断权益投资收益大于 0 或期权内在价值大于 0
]